# Generated by Django 5.1.4 on 2026-04-26 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0098_hscode_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('sale_created', 'Sale Created'), ('sale_refunded', 'Sale Refunded'), ('inventory_updated', 'Inventory Updated'), ('product_changed', 'Product Changed'), ('payment_recorded', 'Payment Recorded')], max_length=50)),
                ('payload', models.JSONField()),
                ('device_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='pos.business')),
            ],
            options={
                'verbose_name': 'Event Log',
                'verbose_name_plural': 'Event Logs',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['tenant', 'sync_status', 'timestamp'], name='events_log_tenant_sync_ts_idx')],
            },
        ),
    ]
