# Generated by Django 5.1.4 on 2026-09-29 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('registration_number', models.CharField(blank=True, help_text='Business Registration Number', max_length=100)),
                ('kra_pin', models.CharField(blank=True, help_text='KRA PIN Number', max_length=50)),
                ('vat_number', models.CharField(blank=True, help_text='VAT Registration Number', max_length=50)),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 Currency Code', max_length=3)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField(default=1, help_text='1=January (Kenya Fiscal Year)')),
                ('timezone', models.CharField(default='Africa/Nairobi', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('county', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Short code e.g. HQ, NBI-01, MSA-01', max_length=20)),
                ('is_headquarters', models.BooleanField(default=False, help_text='Designates this branch as the primary HQ')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('county', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['-is_headquarters', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='LoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('is_successful', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Audit Log',
                'verbose_name_plural': 'Login Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(default='view', help_text='e.g. view, export, decrypt, print', max_length=50)),
                ('entity_type', models.CharField(db_index=True, help_text='e.g. hr.Employee, core.UserProfile', max_length=100)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('fields_accessed', models.JSONField(default=list, help_text="List of protected fields viewed e.g. ['salary', 'kra_pin']")),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_access_logs', to='core.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensitive Data Access Log',
                'verbose_name_plural': 'Sensitive Data Access Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('pin_hash', models.CharField(blank=True, help_text='Hashed 4-6 digit quick PIN', max_length=128)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('force_password_change', models.BooleanField(default=False)),
                ('failed_login_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_active_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.branch')),
                ('last_active_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='BranchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False, help_text="True if this is the user's default branch")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch_role', models.CharField(blank=True, help_text='Branch-specific title or role e.g. Cashier', max_length=30)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_branch_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Membership',
                'verbose_name_plural': 'Branch Memberships',
                'unique_together': {('branch', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner / Director'), ('admin', 'Administrator'), ('manager', 'Manager'), ('staff', 'Staff / Operator'), ('viewer', 'Viewer (Read-Only)')], db_index=True, default='staff', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('custom_permissions', models.JSONField(blank=True, default=list, help_text='List of granted permission codenames')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Membership',
                'verbose_name_plural': 'Company Memberships',
                'unique_together': {('company', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(db_index=True, default='core', max_length=50)),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value_type', models.CharField(choices=[('string', 'String / Text'), ('integer', 'Integer Number'), ('decimal', 'Decimal / Currency'), ('boolean', 'Boolean (True/False)'), ('json', 'Structured JSON / Object')], default='string', max_length=20)),
                ('raw_value', models.TextField(blank=True)),
                ('json_value', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False, help_text='True if safe to expose in client context')),
                ('branch', models.ForeignKey(blank=True, help_text='Branch (NULL for company-wide setting)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_settings', to='core.branch')),
                ('company', models.ForeignKey(blank=True, help_text='Tenant Company (NULL for system-wide defaults)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_settings', to='core.company')),
            ],
            options={
                'verbose_name': 'Core Setting',
                'verbose_name_plural': 'Core Settings',
                'indexes': [models.Index(fields=['module_key', 'key'], name='core_corese_module__889d6a_idx'), models.Index(fields=['company', 'module_key', 'key'], name='core_corese_company_431703_idx')],
                'unique_together': {('company', 'branch', 'module_key', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ModuleActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(db_index=True, help_text="Unique module key e.g. 'pos', 'hr', 'accounting'", max_length=50)),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Per-company module configuration overrides')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_activations', to='core.company')),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module Activation',
                'verbose_name_plural': 'Module Activations',
                'indexes': [models.Index(fields=['company', 'module_key', 'is_enabled'], name='core_module_company_558a81_idx')],
                'unique_together': {('company', 'module_key')},
            },
        ),
    ]
