# Generated by Django 5.1.4 on 2026-09-29 22:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/octet-stream', max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx'), models.Index(fields=['company', 'created_at'], name='core_attach_company_f356e6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('void', 'Voided'), ('login', 'Login'), ('export', 'Data Export'), ('custom', 'Custom Action')], db_index=True, max_length=50)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.company')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'timestamp'], name='core_auditl_company_e9d922_idx'), models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(db_index=True, help_text="e.g. 'sale_invoice', 'purchase_order', 'goods_received_note', 'expense'", max_length=50)),
                ('prefix', models.CharField(default='DOC', max_length=20)),
                ('fiscal_year', models.PositiveSmallIntegerField(db_index=True, default=2026)),
                ('format_pattern', models.CharField(default='{prefix}-{year}{month:02d}-{seq:04d}', help_text='Tokenized pattern e.g. {prefix}-{branch_code}-{year}-{seq:06d}', max_length=100)),
                ('current_number', models.BigIntegerField(default=0)),
                ('is_gap_aware', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch scope (NULL for company-wide sequence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='core.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='core.company')),
            ],
            options={
                'verbose_name': 'Document Sequence',
                'verbose_name_plural': 'Document Sequences',
                'indexes': [models.Index(fields=['company', 'document_type', 'fiscal_year'], name='core_docume_company_c05e5f_idx')],
                'unique_together': {('company', 'branch', 'document_type', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Human-readable job name', max_length=255)),
                ('task_path', models.CharField(help_text='Dotted python path to callable e.g. pos.tasks.generate_report', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('priority', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower number = higher priority')),
                ('args', models.JSONField(blank=True, default=list)),
                ('kwargs', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('locked_by', models.CharField(blank=True, help_text='Worker ID holding lock', max_length=100)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company scoping this job (NULL for system maintenance)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Background Job',
                'verbose_name_plural': 'Background Jobs',
                'ordering': ['priority', 'scheduled_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at', 'priority'], name='core_job_queue_idx'), models.Index(fields=['company', 'status'], name='core_job_company_b1c849_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success'), ('action_required', 'Action Required')], default='info', max_length=20)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('email', 'Email'), ('sms', 'SMS Message'), ('whatsapp', 'WhatsApp')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.company')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'created_at'], name='core_notifi_recipie_4e71b2_idx')],
            },
        ),
    ]
