# Generated by Django 5.1.4 on 2026-09-29 22:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_attachment_auditlog_documentsequence_job_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(db_index=True, help_text="Versioned event name e.g. 'pos.sale_completed.v1', 'hr.employee_hired.v1'", max_length=100)),
                ('payload', models.JSONField(help_text='Serialized event payload dictionary')),
                ('status', models.CharField(choices=[('pending', 'Pending Dispatch'), ('processing', 'Processing Subscribers'), ('dispatched', 'Fully Dispatched'), ('failed', 'Retrying'), ('dead_letter', 'Dead Letter (Exhausted)')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('last_error', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, help_text='Company scoping this event', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='core.company')),
            ],
            options={
                'verbose_name': 'Outbox Event',
                'verbose_name_plural': 'Outbox Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber_name', models.CharField(help_text='Dotted function path of the subscriber', max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.outboxevent')),
            ],
            options={
                'verbose_name': 'Event Delivery',
                'verbose_name_plural': 'Event Deliveries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'Staff Leave Approval', 'Large POS Refund'", max_length=100)),
                ('code', models.CharField(db_index=True, help_text="e.g. 'hr_leave', 'pos_refund', 'supplier_payment'", max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('auto_execute_service', models.CharField(blank=True, help_text='Optional dotted service called when final step is approved', max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.company')),
                ('content_type', models.ForeignKey(help_text='Target entity model being approved', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Workflow Definition',
                'verbose_name_plural': 'Workflow Definitions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(help_text="e.g. 'Department Head Review', 'Director Signoff'", max_length=100)),
                ('approver_role', models.CharField(blank=True, help_text="Role allowed to approve e.g. 'manager', 'admin', 'owner'", max_length=50)),
                ('approver_permission', models.CharField(blank=True, help_text="Permission codename required e.g. 'hr.approve_leave'", max_length=100)),
                ('timeout_hours', models.PositiveIntegerField(default=48)),
                ('approver_user', models.ForeignKey(blank=True, help_text='Specific user assignment (overrides role if set)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflowdefinition')),
            ],
            options={
                'verbose_name': 'Workflow Step',
                'verbose_name_plural': 'Workflow Steps',
                'ordering': ['workflow', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('submission_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.workflowdefinition')),
                ('current_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstep')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('delegate', 'Delegated'), ('escalate', 'Escalated')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('delegated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.approvalrequest')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflowstep')),
            ],
            options={
                'verbose_name': 'Approval Action',
                'verbose_name_plural': 'Approval Actions',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['status', 'created_at'], name='core_outbox_status_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['company', 'event_name'], name='core_outbox_company_d04d9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowdefinition',
            unique_together={('company', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together={('workflow', 'step_number')},
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'company'], name='core_approv_status_4f068b_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='core_approv_content_508d43_idx'),
        ),
    ]
