# Generated by Django 5.1.4 on 2026-09-29 22:49

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_outboxevent_eventdelivery_workflowdefinition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyaBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_code', models.CharField(help_text='CBK Clearing Code (e.g. 01, 11, 68)', max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT / BIC Code', max_length=20)),
                ('paybill_number', models.CharField(blank=True, help_text='M-Pesa Paybill number for bank deposit', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Kenyan Bank',
                'verbose_name_plural': 'Kenyan Banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KenyaCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='County Code (001-047)', max_length=3, unique=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, choices=[('coast', 'Coast'), ('north_eastern', 'North Eastern'), ('eastern', 'Eastern'), ('central', 'Central'), ('rift_valley', 'Rift Valley'), ('western', 'Western'), ('nyanza', 'Nyanza'), ('nairobi', 'Nairobi')], max_length=50)),
            ],
            options={
                'verbose_name': 'Kenya County',
                'verbose_name_plural': 'Kenya Counties',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(db_index=True, help_text='Unique entry reference e.g. JRN-2026-0001', max_length=50)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('source_module', models.CharField(db_index=True, help_text='Origin module e.g. pos, hr, manual', max_length=50)),
                ('source_ref', models.CharField(blank=True, db_index=True, help_text='Origin reference e.g. INV-20260930-0001', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique key preventing double posting', max_length=150, null=True)),
                ('narration', models.TextField(blank=True, help_text='Transaction description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journal_entries', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(db_index=True, help_text='Chart of Accounts code e.g. 1000, 4000', max_length=50)),
                ('account_name', models.CharField(db_index=True, max_length=150)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Period name, e.g. 'January 2026', '2026-Q1'", max_length=50)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False, help_text='True if closed for posting')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'ordering': ['-start_date'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='unique_company_journal_idempotency_key'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('company', 'entry_number')},
        ),
    ]
