# Generated by Django 5.1.4 on 2026-09-30 18:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_kenyabank_kenyacounty_journalentry_journalentryline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='ISO 4217 3-letter code (e.g. KES)', max_length=3, unique=True)),
                ('name', models.CharField(help_text='e.g. Kenyan Shilling, US Dollar', max_length=50)),
                ('symbol', models.CharField(default='KSh', help_text='e.g. KSh, $, €, £', max_length=10)),
                ('decimal_places', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Piece, Kilogram, Carton', max_length=50)),
                ('code', models.CharField(db_index=True, help_text='e.g. PCS, KG, CTN', max_length=20)),
                ('category', models.CharField(choices=[('unit', 'Unit / Quantity (e.g. PCS, Box, Carton)'), ('weight', 'Weight (e.g. Kg, Gram, Ton)'), ('volume', 'Volume (e.g. Liter, Milliliter, Gallon)'), ('length', 'Length (e.g. Meter, Centimeter, Foot)'), ('time', 'Time / Duration (e.g. Hour, Day, Month)')], default='unit', max_length=20)),
                ('is_base_unit', models.BooleanField(default=False, help_text='If True, this is the reference unit for this category (conversion factor = 1.0)')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
            ],
            options={
                'verbose_name': 'Unit of Measure',
                'verbose_name_plural': 'Units of Measure',
                'ordering': ['category', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate to multiply from_currency by to get to_currency', max_digits=16, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('effective_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('source', models.CharField(blank=True, default='Manual', help_text='e.g. Central Bank of Kenya / Manual', max_length=100)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('from_currency', models.ForeignKey(help_text='Source currency (e.g. USD)', on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='core.currency')),
                ('to_currency', models.ForeignKey(help_text='Base currency (e.g. KES)', on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='core.currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ['-effective_date'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='core_exchange_rate_positive')],
                'unique_together': {('company', 'from_currency', 'to_currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('party_type', models.CharField(choices=[('customer', 'Customer / Debtor'), ('vendor', 'Vendor / Creditor'), ('both', 'Customer & Vendor'), ('internal', 'Internal / Inter-Branch')], db_index=True, default='customer', max_length=20)),
                ('code', models.CharField(db_index=True, help_text='Unique Party Code e.g. CUST-0001, VEND-0001', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_pin', models.CharField(blank=True, db_index=True, help_text='KRA PIN or Tax Registration ID', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, default='Nairobi', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum allowed credit balance', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('credit_period_days', models.PositiveIntegerField(default=0, help_text='Standard credit terms in days')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate / Cash on Delivery'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days')], default='immediate', max_length=20)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('mpesa_paybill', models.CharField(blank=True, max_length=30)),
                ('mpesa_account_reference', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('legacy_pos_customer_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_pos_supplier_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_accounting_customer_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('legacy_accounting_vendor_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='core.kenyabank')),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parties', to='core.kenyacounty')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['company', 'party_type', 'is_active'], name='core_party_company_772838_idx'), models.Index(fields=['company', 'tax_pin'], name='core_party_company_2a10a8_idx'), models.Index(fields=['company', 'phone'], name='core_party_company_870597_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('credit_limit__gte', 0)), name='core_party_credit_limit_non_negative')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. Standard VAT 16%, Zero-Rated 0%, Exempt', max_length=100)),
                ('code', models.CharField(db_index=True, help_text='Short code e.g. VAT-16, VAT-0, EXEMPT', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Tax percentage rate (e.g. 16.00 for 16%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('tax_type', models.CharField(choices=[('vat', 'Value Added Tax (VAT)'), ('withholding', 'Withholding Tax'), ('excise', 'Excise Duty'), ('other', 'Other Levy / Tax')], default='vat', max_length=20)),
                ('kra_etims_code', models.CharField(blank=True, help_text="KRA eTIMS Code: 'A' (16%), 'B' (0%), 'C' (Exempt), 'D' (Non-VAT), 'E' (8%)", max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Default tax rate applied to new products')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
            ],
            options={
                'verbose_name': 'Tax Rate',
                'verbose_name_plural': 'Tax Rates',
                'ordering': ['-rate', 'name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='core_tax_rate_percentage_valid_range')],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UOMConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text='Multiply from_uom quantity by this factor to obtain to_uom quantity', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('from_uom', models.ForeignKey(help_text='Source unit (e.g. Carton)', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='core.unitofmeasure')),
                ('to_uom', models.ForeignKey(help_text='Target base unit (e.g. Piece)', on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='core.unitofmeasure')),
            ],
            options={
                'verbose_name': 'UOM Conversion',
                'verbose_name_plural': 'UOM Conversions',
                'constraints': [models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='core_uom_conversion_factor_positive')],
                'unique_together': {('company', 'from_uom', 'to_uom')},
            },
        ),
    ]
