"""
Django settings for pos_system project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
def load_env_file():
    """Load .env file manually if python-dotenv is not available"""
    env_file = BASE_DIR / '.env'
    if env_file.exists():
        with open(env_file, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    if key and value:
                        os.environ.setdefault(key, value)

try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    # python-dotenv not installed, load manually
    load_env_file()

# ==================== SENTRY ERROR TRACKING ====================
# Initialize Sentry for error tracking and performance monitoring
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    
    SENTRY_DSN = os.environ.get('SENTRY_DSN', '')
    if SENTRY_DSN:
        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=0.1,  # 10% of transactions for performance monitoring
            send_default_pii=False,  # Don't send personally identifiable information
            environment="production" if not DEBUG else "development",
            # Set release version if available
            release=os.environ.get('HEROKU_SLUG_COMMIT', 'unknown'),
        )
except ImportError:
    # Sentry SDK not installed - skip initialization
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-vpn)fmw-z%^9o@my_d#x4jkcgo$1c0a27qm81kp@sxx5ts3q9)')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# Test mode - bypasses authentication (ONLY FOR TESTING!)
TEST_MODE = os.environ.get('TEST_MODE', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []

# Auto-detect Back4App and other cloud platforms
if not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['*']  # Allow all hosts if not specified

# CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Auto-add common cloud platform patterns
if not CSRF_TRUSTED_ORIGINS:
    # Automatically trust Back4App, Render, and common platforms
    CSRF_TRUSTED_ORIGINS = [
        'https://*.b4a.run',
        'https://*.onrender.com',
        'https://*.herokuapp.com',
    ]
    # Add localhost for development
    if DEBUG:
        CSRF_TRUSTED_ORIGINS.extend([
            'http://localhost:8000',
            'http://127.0.0.1:8000',
            'http://localhost',
            'http://127.0.0.1',
        ])
    # Add current host if available
    import socket
    try:
        hostname = socket.gethostname()
        if hostname:
            CSRF_TRUSTED_ORIGINS.append(f'https://{hostname}')
    except:
        pass


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Modern admin theme - must be before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_spectacular',
    'django_ratelimit',
    'pos',
    'hr',
    'events',
    'sync',
    'backup',
    'restore',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'pos.middleware.AuditRequestMiddleware',  # Attach request to audit logs
    'django.contrib.messages.middleware.MessageMiddleware',  # Move before TenantMiddleware
    'pos.middleware.TenantMiddleware',  # Multi-tenancy middleware
    'pos.middleware.BranchMiddleware',  # Multi-branch context
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Add TestModeMiddleware if TEST_MODE is enabled
if TEST_MODE:
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.contrib.messages.middleware.MessageMiddleware'),
        'pos.middleware.TestModeMiddleware'
    )
    print("⚠️  TEST_MODE ENABLED - Authentication bypassed! Only use for testing!")

ROOT_URLCONF = 'pos_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pos.permissions.user_permissions',  # Add permission context processor
                'pos.context_processors.business_context',  # Add business context processor
            ],
        },
    },
]

WSGI_APPLICATION = 'pos_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

import dj_database_url

# Database configuration with support for PostgreSQL, MySQL, and SQLite
if os.environ.get('DATABASE_URL'):
    # Use DATABASE_URL if provided (Heroku, Render, etc.)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
    # Ensure connection pooling options are set
    DATABASES['default'].setdefault('CONN_MAX_AGE', 600)
    DATABASES['default'].setdefault('OPTIONS', {})
    if 'postgresql' in DATABASES['default'].get('ENGINE', ''):
        DATABASES['default']['OPTIONS'].setdefault('connect_timeout', 10)
        DATABASES['default']['OPTIONS'].setdefault('options', '-c statement_timeout=30000')
elif os.environ.get('DATABASE_ENGINE'):
    # Use environment variables for database configuration
    db_engine = os.environ.get('DATABASE_ENGINE', 'postgresql').lower()
    
    if db_engine == 'postgresql':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.environ.get('DATABASE_NAME', 'pos_db'),
                'USER': os.environ.get('DATABASE_USER', 'pos_user'),
                'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
                'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
                'PORT': os.environ.get('DATABASE_PORT', '5432'),
                'CONN_MAX_AGE': 600,
                'OPTIONS': {
                    'connect_timeout': 10,
                },
            }
        }
    elif db_engine == 'mysql':
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.mysql',
                'NAME': os.environ.get('DATABASE_NAME', 'pos_db'),
                'USER': os.environ.get('DATABASE_USER', 'pos_user'),
                'PASSWORD': os.environ.get('DATABASE_PASSWORD', ''),
                'HOST': os.environ.get('DATABASE_HOST', 'localhost'),
                'PORT': os.environ.get('DATABASE_PORT', '3306'),
                'CONN_MAX_AGE': 600,
                'OPTIONS': {
                    'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
                    'charset': 'utf8mb4',
                },
            }
        }
    else:
        # Fallback to SQLite
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }
else:
    # Default to SQLite for development
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Read replica support (optional) — set DATABASE_REPLICA_URL in .env for reporting queries
_replica_url = os.environ.get('DATABASE_REPLICA_URL', '')
if _replica_url:
    DATABASES['replica'] = dj_database_url.config(
        default=_replica_url,
        conn_max_age=600,
        conn_health_checks=True,
    )
    DATABASE_ROUTERS = ['pos.db_router.ReplicaRouter']


# Cache Configuration
# https://docs.djangoproject.com/en/4.2/ref/settings/#caches

# Redis cache configuration
# Falls back to local memory cache if Redis is not available
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1')

# Try to import django_redis to check if it's available
try:
    import django_redis
    REDIS_AVAILABLE = True
except ImportError:
    REDIS_AVAILABLE = False

# Check if Redis is actually running by attempting a connection
def is_redis_running():
    """Check if Redis server is running and accessible."""
    if not REDIS_AVAILABLE:
        return False
    try:
        import redis
        r = redis.Redis.from_url(REDIS_URL, socket_connect_timeout=2, socket_timeout=2)
        r.ping()
        return True
    except Exception:
        return False

# Determine if we can use Redis
REDIS_RUNNING = is_redis_running()

if REDIS_AVAILABLE and REDIS_RUNNING:
    # Use Redis if available and running
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
                'RETRY_ON_TIMEOUT': True,
                'MAX_CONNECTIONS': 50,
                'CONNECTION_POOL_CLASS_KWARGS': {
                    'max_connections': 50,
                    'retry_on_timeout': True,
                },
            },
            'KEY_PREFIX': 'pos',
            'TIMEOUT': 300,  # 5 minutes default
        },
        'ratelimit': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'SOCKET_CONNECT_TIMEOUT': 5,
                'SOCKET_TIMEOUT': 5,
            },
            'KEY_PREFIX': 'ratelimit',
        },
        'locmem': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }
else:
    # Development fallback (no Redis) - disable rate limiting entirely
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        },
        'locmem': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'unique-snowflake',
        }
    }

# Rate Limiting Configuration
# Only enable rate limiting when Redis is available (requires atomic increment support)
if REDIS_AVAILABLE and REDIS_RUNNING:
    RATELIMIT_CACHE = 'ratelimit'
    RATELIMIT_ENABLE = True
else:
    RATELIMIT_ENABLE = False
    # Silence django_ratelimit system checks when Redis is not available
    SILENCED_SYSTEM_CHECKS = ['django_ratelimit.E003', 'django_ratelimit.W001']

# Cache time settings (in seconds)
CACHE_TTL = {
    'dashboard': 300,       # 5 minutes
    'reports': 600,         # 10 minutes
    'products': 1800,       # 30 minutes
    'categories': 3600,     # 1 hour
    'customers': 900,       # 15 minutes
    'business_settings': 3600,
    'payment_methods': 3600,
    'loyalty_rewards': 3600,
}


# ============================================
# EMAIL CONFIGURATION
# ============================================

# Email backend
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'  # Console for development
)

# SMTP Configuration
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'in-v3.mailjet.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@yourpos.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Email settings
EMAIL_TIMEOUT = 10
EMAIL_USE_LOCALTIME = True

# For Mailjet, you need to:
# 1. Verify your sender/domain in Mailjet
# 2. Use Mailjet API key as EMAIL_HOST_USER
# 3. Use Mailjet secret key as EMAIL_HOST_PASSWORD
#
# Example .env configuration:
# EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
# EMAIL_HOST=in-v3.mailjet.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=your_mailjet_api_key
# EMAIL_HOST_PASSWORD=your_mailjet_secret_key
# DEFAULT_FROM_EMAIL=verified-sender@yourdomain.com


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'pos.validators.UppercaseValidator',
    },
    {
        'NAME': 'pos.validators.LowercaseValidator',
    },
    {
        'NAME': 'pos.validators.NumberValidator',
    },
    {
        'NAME': 'pos.validators.SpecialCharValidator',
    },
    {
        'NAME': 'pos.validators.PasswordHistoryValidator',
        'OPTIONS': {'history_count': 5},
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ── CDN / Storage backend ────────────────────────────────────────────────────
# Set AWS_S3_CUSTOM_DOMAIN (or CDN_DOMAIN) in .env to activate S3+CDN storage.
# Without it, falls back to WhiteNoise (static) + local filesystem (media).

_CDN_DOMAIN = os.environ.get('CDN_DOMAIN', '')          # e.g. d1234.cloudfront.net
_AWS_BUCKET = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')

if _AWS_BUCKET:
    # django-storages S3 backend
    INSTALLED_APPS += ['storages']

    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = _AWS_BUCKET
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = _CDN_DOMAIN or f'{_AWS_BUCKET}.s3.amazonaws.com'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age=86400'}
    AWS_QUERYSTRING_AUTH = False

    # Static files → S3/CDN
    STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'
    STATIC_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/static/'

    # Media files → S3/CDN
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'

else:
    # WhiteNoise for static files (no CDN)
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Marid POS Settings
VAT_RATE = 16  # Kenya VAT rate
SHOP_NAME = 'My Retail Shop'


# Authentication Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Session security — expire on browser close, short max age
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 28800          # 8 hours max (safety net)
SESSION_COOKIE_SECURE = not DEBUG   # HTTPS only in production
SESSION_COOKIE_HTTPONLY = True      # No JS access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'     # CSRF protection

# Password Reset Token Expiry (in seconds)
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours

# Field-level encryption key for sensitive data at rest
# Generate with: python -c "from pos.encryption import generate_key; print(generate_key())"
# Store in .env as FIELD_ENCRYPTION_KEY=<generated_key>
FIELD_ENCRYPTION_KEY = os.environ.get('FIELD_ENCRYPTION_KEY', '')


# ==================== CELERY CONFIGURATION ====================

CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 300          # 5 min hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240     # 4 min soft limit (raises SoftTimeLimitExceeded)
CELERY_WORKER_PREFETCH_MULTIPLIER = 1 # Fair task distribution
CELERY_TASK_ACKS_LATE = True          # Re-queue on worker crash
CELERY_TASK_ROUTES = {
    'pos.tasks.send_campaign_emails': {'queue': 'emails'},
    'pos.tasks.send_purchase_order_email': {'queue': 'emails'},
    'pos.tasks.send_payment_confirmation_email': {'queue': 'emails'},
    'pos.tasks.send_grn_notification_email': {'queue': 'emails'},
    'pos.tasks.send_license_expiry_reminder': {'queue': 'emails'},
    'pos.tasks.generate_analytics_report': {'queue': 'reports'},
    'pos.tasks.export_report_csv': {'queue': 'reports'},
}


# ==================== REST FRAMEWORK CONFIGURATION ====================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'pos.api_authentication.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DATETIME_FORMAT': '%Y-%m-%d %H:%M:%S',
    'DATE_FORMAT': '%Y-%m-%d',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
        'auth': '5/minute',  # Stricter limits for authentication
        'login': '3/minute',  # Very strict for login attempts
    },
}

# Customer module safeguards
ENFORCE_UNIQUE_CUSTOMER_PHONE = os.environ.get('ENFORCE_UNIQUE_CUSTOMER_PHONE', 'true').lower() == 'true'

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=24),  # Long-lived for offline capability
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,  # Allow offline refresh
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS Settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CORS_ALLOW_CREDENTIALS = True

# For development - allow all origins (REMOVE IN PRODUCTION)
CORS_ALLOW_ALL_ORIGINS = DEBUG

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Marid POS API',
    'DESCRIPTION': 'REST API for offline-first Marid POS with cloud sync',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'POSTPROCESSING_HOOKS': [],          # disable hooks that can crash on introspection
    'DISABLE_ERRORS_AND_WARNINGS': True, # suppress schema generation errors
}


# ==================== JAZZMIN ADMIN THEME CONFIGURATION ====================

JAZZMIN_SETTINGS = {
    # Title on the login screen and header
    "site_title": "Marid POS",
    "site_header": "General Admin",
    "site_brand": "Marid POS",
    "site_logo": None,  # Can add logo path here later
    "login_logo": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    
    # Welcome text on the login screen
    "welcome_sign": "Welcome to General Admin",
    
    # Copyright on the footer
    "copyright": "Marid POS",
    
    # The model admin to search from the search bar, search bar omitted if excluded
    "search_model": ["auth.User", "pos.Product", "pos.Customer"],
    
    # Field name on user model that contains avatar
    "user_avatar": None,
    
    ############
    # Top Menu #
    ############
    
    # Links to put along the top menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Back to Frontend", "url": "/businesses/", "permissions": ["auth.view_user"], "icon": "fas fa-arrow-left"},
        {"model": "auth.User"},
        {"app": "pos"},
    ],
    
    #############
    # User Menu #
    #############
    
    # Additional links to include in the user menu on the top right
    "usermenu_links": [
        {"name": "My Businesses", "url": "/businesses/", "icon": "fas fa-store"},
        {"model": "auth.user"},
    ],
    
    #############
    # Side Menu #
    #############
    
    # Whether to display the side menu
    "show_sidebar": True,
    
    # Whether to aut expand the menu
    "navigation_expanded": True,
    
    # Hide these apps when generating side menu
    "hide_apps": [],
    
    # Hide these models when generating side menu
    "hide_models": [],
    
    # List of apps (and/or models) to base side menu ordering off of
    "order_with_respect_to": [
        "auth",
        "pos.Product",
        "pos.Category",
        "pos.Sale",
        "pos.Customer",
        "pos.Supplier",
        "pos.Purchase",
    ],
    
    # Custom links to append to app groups, keyed on app name
    "custom_links": {
        "pos": [{
            "name": "My Businesses",
            "url": "/businesses/",
            "icon": "fas fa-store",
            "permissions": ["pos.view_product"]
        }]
    },
    
    # Custom icons for side menu apps/models
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "pos.Product": "fas fa-box",
        "pos.Category": "fas fa-tags",
        "pos.Sale": "fas fa-shopping-cart",
        "pos.SaleItem": "fas fa-list",
        "pos.Customer": "fas fa-user-friends",
        "pos.Supplier": "fas fa-truck",
        "pos.Purchase": "fas fa-shopping-bag",
        "pos.PurchaseItem": "fas fa-list-ul",
        "pos.StockAdjustment": "fas fa-boxes",
        "pos.UserProfile": "fas fa-id-card",
        "pos.BusinessSettings": "fas fa-cog",
        "pos.ActivityLog": "fas fa-history",
        "pos.LoyaltyTransaction": "fas fa-coins",
        "pos.LoyaltyReward": "fas fa-gift",
        "pos.LoyaltyRedemption": "fas fa-ticket-alt",
        "pos.PaymentMethod": "fas fa-credit-card",
        "pos.SalePayment": "fas fa-money-bill-wave",
        "pos.Shift": "fas fa-clock",
        "pos.SaleReturn": "fas fa-undo",
        "pos.BackupAuditLog": "fas fa-lock",
    }
}

# =============================================================================
# BACKUP & SECURITY SETTINGS
# =============================================================================

# Enable GPG encryption for all backups (requires gpg command available)
BACKUP_ENABLE_ENCRYPTION = os.environ.get('BACKUP_ENABLE_ENCRYPTION', 'True') == 'True'

# GPG recipient (public key ID) for backup encryption
# Generate with: gpg --list-keys (copy the long key ID)
BACKUP_GPG_RECIPIENT = os.environ.get('BACKUP_GPG_RECIPIENT', '')

# GPG passphrase for symmetric encryption (if no recipient)
BACKUP_GPG_PASSPHRASE = os.environ.get('BACKUP_GPG_PASSPHRASE', '')

# Backup retention policies (in days)
BACKUP_RETENTION_DAILY = int(os.environ.get('BACKUP_RETENTION_DAILY', 7))  # Keep daily backups for 7 days
BACKUP_RETENTION_WEEKLY = int(os.environ.get('BACKUP_RETENTION_WEEKLY', 30))  # Keep weekly for 30 days
BACKUP_RETENTION_MONTHLY = int(os.environ.get('BACKUP_RETENTION_MONTHLY', 365))  # Keep monthly for 1 year

# Cloud backup storage (optional)
BACKUP_S3_BUCKET = os.environ.get('BACKUP_S3_BUCKET', '')
BACKUP_GCS_BUCKET = os.environ.get('BACKUP_GCS_BUCKET', '')
BACKUP_AZURE_CONNECTION_STRING = os.environ.get('BACKUP_AZURE_CONNECTION_STRING', '')
BACKUP_AZURE_CONTAINER = os.environ.get('BACKUP_AZURE_CONTAINER', '')

# Force HTTPS/TLS for all cloud uploads (security best practice)
BACKUP_FORCE_TLS = os.environ.get('BACKUP_FORCE_TLS', 'True') == 'True'

# Automated disaster recovery testing (test restore weekly)
BACKUP_TEST_RESTORE_ENABLED = os.environ.get('BACKUP_TEST_RESTORE_ENABLED', 'True') == 'True'
BACKUP_TEST_RESTORE_SCHEDULE = os.environ.get('BACKUP_TEST_RESTORE_SCHEDULE', 'weekly')  # daily, weekly, monthly


# Jazzmin UI Tweaks
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",  # Options: default, cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, pulse, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, yeti
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}


# Site URL for email links
SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# Multi-Branch plan limits
BRANCH_LIMITS = {
    'trial': 3,
    'free': 3,
    'paid': 3,   # Hard cap at 3 to prevent system overload
}
