# Generated by Django 5.1.4 on 2026-04-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0098_hscode_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('pending_events_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('synced', 'Synced'), ('pending', 'Pending'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_statuses', to='pos.business')),
            ],
            options={
                'verbose_name': 'Sync Status',
                'verbose_name_plural': 'Sync Statuses',
                'unique_together': {('tenant', 'device_id')},
            },
        ),
    ]
