# Generated by Django 5.2.12 on 2026-04-05 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_optional_user_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='deductions',
        ),
        migrations.AddField(
            model_name='employee',
            name='house_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly house allowance', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly medical allowance', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly other allowances', max_digits=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly transport allowance', max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='house_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='nssf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='nhif',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='payroll',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
