# Generated by Django 5.2.12 on 2026-04-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_rename_deductions_payroll_nhif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='KRA PIN for tax purposes', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nhif_number',
            field=models.CharField(help_text='NHIF number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(help_text='NSSF number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='paye_number',
            field=models.CharField(help_text='PAYE number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='staff_code',
            field=models.CharField(editable=False, help_text='Auto-generated staff code', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(help_text='National ID number', max_length=50, null=True),
        ),
    ]
