# Generated by Django 5.2.12 on 2026-04-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_employee_kra_pin_employee_nhif_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='paye_number',
        ),
    ]
