# Generated by Django 5.2.12 on 2026-04-05 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_employee_paye_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='other_allowances',
            field=models.JSONField(blank=True, default=dict, help_text="Additional custom allowances as JSON {'name': amount, ...}"),
        ),
        migrations.AddField(
            model_name='payroll',
            name='other_allowances_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total of additional custom allowances', max_digits=10),
        ),
    ]
