# Generated by Django 5.1.4 on 2026-09-29 21:35

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_employee_basic_salary'),
        ('pos', '0110_suppliercredit_suppliercreditapplication_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KenyanBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bank_code', models.CharField(help_text='Central Bank of Kenya clearing code', max_length=20, unique=True)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='employee_accompanied_by',
            field=models.CharField(blank=True, help_text='Name of fellow employee or shop floor union rep', max_length=150),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disciplinaryrecord',
            name='hearing_held',
            field=models.BooleanField(default=False, help_text='Formal hearing conducted per Employment Act Sec. 41'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank Account Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch',
            field=models.CharField(blank=True, help_text='Branch Name', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_branch_code',
            field=models.CharField(blank=True, help_text='Branch Sort Code', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_code',
            field=models.CharField(blank=True, help_text='Bank Clearing Code', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank Name', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='county',
            field=models.CharField(blank=True, choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', "Murang'a"), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita-Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka-Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('pokot', 'West Pokot')], help_text='County of residence', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='disability_cert_number',
            field=models.CharField(blank=True, help_text='NCPWD Registration Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='disability_exemption_cert',
            field=models.CharField(blank=True, help_text='KRA Tax Exemption Certificate Number', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='disability_exemption_expiry',
            field=models.DateField(blank=True, help_text='KRA PWD Exemption Expiry Date', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='disability_status',
            field=models.BooleanField(default=False, help_text='Registered Person with Disability (NCPWD)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='helb_number',
            field=models.CharField(blank=True, help_text='HELB loan account reference', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('alien_id', 'Alien ID Card / Refugee ID'), ('military_id', 'Military ID')], default='national_id', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_non_resident',
            field=models.BooleanField(default=False, help_text='Non-resident for tax purposes (flat withholding rate)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_secondary_employee',
            field=models.BooleanField(default=False, help_text='Secondary employment (No personal relief granted)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='mpesa_number',
            field=models.CharField(blank=True, help_text='M-Pesa B2C salary payment phone e.g. +254712345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan format (e.g. +254712345678, 0712345678, or 0112345678).', regex='^(?:\\+254|0)?[17]\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='Kenyan', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='nita_number',
            field=models.CharField(blank=True, help_text='NITA apprentice/employer registration number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Official contact phone e.g. +254712345678', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number must be a valid Kenyan format (e.g. +254712345678, 0712345678, or 0112345678).', regex='^(?:\\+254|0)?[17]\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='employee',
            name='sha_number',
            field=models.CharField(blank=True, help_text='Social Health Authority (SHA) registration number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_permit_type',
            field=models.CharField(blank=True, help_text='Class D, Class G, etc. for foreign nationals', max_length=50),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employer_housing_levy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Employer Matching Housing Levy (1.5%)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employer_nita',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Employer NITA Levy (KES 50)'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='employer_nssf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Employer Matching NSSF'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='helb_deduction',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='HELB Loan Deduction'),
        ),
        migrations.AlterField(
            model_name='disciplinaryrecord',
            name='incident_type',
            field=models.CharField(choices=[('show_cause', 'Show Cause Notice Issued'), ('verbal_warning', 'Verbal Warning'), ('written_warning_1', '1st Written Warning'), ('written_warning_final', 'Final Written Warning'), ('suspension', 'Suspension Pending Inquiry'), ('termination', 'Fair Termination / Dismissal'), ('other', 'Other Incident')], max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(help_text='National ID / Passport Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='KRA PIN (Format: A012345678X)', max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='KRA PIN must be exactly 11 characters: 1 uppercase letter, 9 digits, and 1 uppercase letter (e.g. A012345678X).', regex='^[A-Z]\\d{9}[A-Z]$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nhif_number',
            field=models.CharField(blank=True, help_text='Legacy NHIF number (historical records)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nssf_number',
            field=models.CharField(help_text='NSSF Member Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave (21 Working Days Min)'), ('sick', 'Sick Leave (30 Full Pay / 15 Half Pay)'), ('maternity', 'Maternity Leave (3 Months Paid)'), ('paternity', 'Paternity Leave (2 Weeks Paid)'), ('emergency', 'Compassionate / Emergency Leave'), ('study', 'Study / Exam Leave'), ('unpaid', 'Unpaid Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='housing_levy',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Affordable Housing Levy (1.5% Employee)'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='nssf',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='NSSF (Employee Tier I + II)'),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='e.g. Payroll Processing, Biometric Attendance, Statutory Returns', max_length=200)),
                ('is_consented', models.BooleanField(default=True)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('privacy_policy_version', models.CharField(default='KE-DPA-2024-V1', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='hr.employee')),
            ],
            options={
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBreachIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('detected_at', models.DateTimeField()),
                ('odpc_notification_deadline', models.DateTimeField(help_text='72 hours from detection')),
                ('odpc_notified_at', models.DateTimeField(blank=True, null=True)),
                ('odpc_reference_number', models.CharField(blank=True, max_length=100)),
                ('affected_subjects_count', models.PositiveIntegerField(default=0)),
                ('remediation_steps', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('detected', 'Detected / Investigating'), ('contained', 'Contained'), ('reported_odpc', 'Reported to ODPC'), ('resolved', 'Resolved & Closed')], default='detected', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breach_incidents', to='pos.business')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('access', 'Right to Access (Copy of Personal Data)'), ('rectification', 'Right to Rectification (Correction)'), ('erasure', 'Right to Erasure / Anonymization'), ('restriction', 'Right to Restrict Processing'), ('portability', 'Right to Data Portability (JSON/CSV Export)'), ('objection', 'Right to Object to Processing')], max_length=30)),
                ('details', models.TextField()),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(help_text='Statutory 30-day deadline per DPA 2019')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_requests', to='pos.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsr_requests', to='hr.employee')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveDataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_category', models.CharField(choices=[('salary_payroll', 'Salary & Compensation'), ('national_id_passport', 'National ID / Passport / Bio'), ('medical_health', 'Medical Notes & Health Certs'), ('disciplinary', 'Disciplinary Hearings & Show Cause'), ('banking_pin', 'Banking Details & PIN')], max_length=30)),
                ('action', models.CharField(choices=[('view', 'Viewed Record'), ('edit', 'Updated Record'), ('export', 'Exported Report / CSV'), ('download', 'Downloaded File / PDF')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_data_logs', to='pos.business')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='hr.employee')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='StatutoryRuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Kenya Statutory Rules — 2026 Edition', max_length=150)),
                ('version_code', models.CharField(help_text='e.g. KE-2026-V1', max_length=50)),
                ('effective_from', models.DateField(help_text='Date when this rule-set becomes active')),
                ('effective_to', models.DateField(blank=True, help_text='Leave blank if currently active / open-ended', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Gazette notice / Finance Act citation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statutory_rulesets', to='pos.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-created_at'],
                'unique_together': {('business', 'version_code')},
            },
        ),
        migrations.CreateModel(
            name='SHIFRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_rate', models.DecimalField(decimal_places=2, default=Decimal('2.75'), max_digits=5)),
                ('minimum_contribution', models.DecimalField(decimal_places=2, default=Decimal('300.00'), max_digits=10)),
                ('maximum_contribution', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_allowable_deduction', models.BooleanField(default=False, help_text='Treated as allowable deduction before PAYE calculation')),
                ('ruleset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shif_rule', to='hr.statutoryruleset')),
            ],
        ),
        migrations.CreateModel(
            name='NITARule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_employer_levy', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Flat monthly employer levy per employee', max_digits=8)),
                ('ruleset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nita_rule', to='hr.statutoryruleset')),
            ],
        ),
        migrations.CreateModel(
            name='HousingLevyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('is_allowable_deduction', models.BooleanField(default=True, help_text='Allowable deduction for PAYE tax purposes')),
                ('ruleset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='housing_levy_rule', to='hr.statutoryruleset')),
            ],
        ),
        migrations.AddField(
            model_name='payroll',
            name='ruleset_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls_processed', to='hr.statutoryruleset'),
        ),
        migrations.CreateModel(
            name='StatutoryReliefRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relief_type', models.CharField(choices=[('personal', 'Personal Relief (Monthly)'), ('insurance', 'Insurance Relief (Health/Life Premiums)'), ('disability', 'Disability (PWD) Monthly Tax Exemption'), ('pension_cap', 'Defined Pension / Provident Fund Monthly Cap'), ('mortgage_cap', 'Owner-Occupied Mortgage Interest Monthly Cap'), ('post_retirement_medical', 'Post-Retirement Medical Fund Monthly Cap')], max_length=40)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='e.g. 15% for insurance relief', max_digits=5)),
                ('maximum_monthly_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='e.g. 5,000 max monthly insurance relief', max_digits=12)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relief_rules', to='hr.statutoryruleset')),
            ],
            options={
                'ordering': ['ruleset', 'relief_type'],
                'unique_together': {('ruleset', 'relief_type')},
            },
        ),
        migrations.CreateModel(
            name='PAYETaxBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_order', models.PositiveIntegerField(default=1)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('upper_limit', models.DecimalField(blank=True, decimal_places=2, help_text='Null for the topmost bracket', max_digits=12, null=True)),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='e.g. 10.00, 25.00, 30.00, 32.50, 35.00', max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paye_bands', to='hr.statutoryruleset')),
            ],
            options={
                'ordering': ['ruleset', 'band_order'],
                'unique_together': {('ruleset', 'band_order')},
            },
        ),
        migrations.CreateModel(
            name='NSSFTierRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(choices=[('tier_1', 'Tier I (Lower Earnings Limit)'), ('tier_2', 'Tier II (Upper Earnings Limit)')], max_length=20)),
                ('lower_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('employee_rate', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('employer_rate', models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=5)),
                ('max_employee_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_employer_contribution', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nssf_tiers', to='hr.statutoryruleset')),
            ],
            options={
                'ordering': ['ruleset', 'tier_name'],
                'unique_together': {('ruleset', 'tier_name')},
            },
        ),
    ]
