# Generated by Django 5.1.4 on 2026-09-30 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_kenyanbank_and_more'),
        ('pos', '0111_posglmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRGLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salaries_expense_code', models.CharField(default='6000', help_text='Salaries & Wages Expense (default: 6000)', max_length=20)),
                ('employer_nssf_expense_code', models.CharField(default='6010', help_text='NSSF Employer Expense (default: 6010)', max_length=20)),
                ('employer_shif_expense_code', models.CharField(default='6020', help_text='SHIF Employer Expense (default: 6020)', max_length=20)),
                ('employer_housing_levy_expense_code', models.CharField(default='6030', help_text='Housing Levy Employer Expense (default: 6030)', max_length=20)),
                ('employer_nita_expense_code', models.CharField(default='6040', help_text='NITA Employer Expense (default: 6040)', max_length=20)),
                ('net_salaries_payable_code', models.CharField(default='2200', help_text='Net Salaries Payable (default: 2200)', max_length=20)),
                ('paye_payable_code', models.CharField(default='2110', help_text='PAYE Payable (default: 2110)', max_length=20)),
                ('nssf_payable_code', models.CharField(default='2120', help_text='NSSF Deductions Payable (default: 2120)', max_length=20)),
                ('shif_payable_code', models.CharField(default='2130', help_text='SHIF Deductions Payable (default: 2130)', max_length=20)),
                ('housing_levy_payable_code', models.CharField(default='2140', help_text='Housing Levy Payable (default: 2140)', max_length=20)),
                ('helb_payable_code', models.CharField(default='2150', help_text='HELB Deductions Payable (default: 2150)', max_length=20)),
                ('staff_advances_asset_code', models.CharField(default='1150', help_text='Staff Advances Asset (default: 1150)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hr_gl_mapping', to='pos.business')),
            ],
            options={
                'verbose_name': 'HR GL Mapping',
                'verbose_name_plural': 'HR GL Mappings',
            },
        ),
    ]
