# Generated by Django 5.1.4 on 2026-09-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_hrglmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrglmapping',
            name='nita_payable_code',
            field=models.CharField(default='2160', help_text='NITA Levy Payable (default: 2160)', max_length=20),
        ),
        migrations.AlterField(
            model_name='hrglmapping',
            name='employer_housing_levy_expense_code',
            field=models.CharField(default='6040', help_text='Housing Levy Employer Expense (default: 6040)', max_length=20),
        ),
        migrations.AlterField(
            model_name='hrglmapping',
            name='employer_nita_expense_code',
            field=models.CharField(default='6050', help_text='NITA Employer Expense (default: 6050)', max_length=20),
        ),
        migrations.AlterField(
            model_name='hrglmapping',
            name='employer_nssf_expense_code',
            field=models.CharField(default='6030', help_text='NSSF Employer Expense (default: 6030)', max_length=20),
        ),
        migrations.AlterField(
            model_name='hrglmapping',
            name='staff_advances_asset_code',
            field=models.CharField(default='1310', help_text='Staff Advances Asset (default: 1310)', max_length=20),
        ),
    ]
