# Generated by Django 5.1.4 on 2026-09-30 19:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_currency_unitofmeasure_exchangerate_party_taxrate_and_more'),
        ('pos', '0111_posglmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('adjustment_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('physical_count', 'Physical Stock Count Reconciliation'), ('damage', 'Damaged / Broken Goods'), ('expiry', 'Expired Stock Disposal'), ('theft_loss', 'Theft / Shrinkage Loss'), ('correction', 'Data Correction')], default='physical_count', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted to Ledger'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('total_variance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Adjustment Document',
                'verbose_name_plural': 'Stock Adjustment Documents',
                'ordering': ['-adjustment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('counted_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('variance_quantity', models.DecimalField(decimal_places=4, help_text='counted_quantity - system_quantity', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('total_variance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustmentdocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
            ],
            options={
                'verbose_name': 'Stock Adjustment Line',
                'verbose_name_plural': 'Stock Adjustment Lines',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(db_index=True, help_text='Unique Warehouse Code e.g. WH-HQ, WH-CBD', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('warehouse_type', models.CharField(choices=[('main', 'Main Warehouse / Bulk Storage'), ('store', 'Retail Store / Front Shelf'), ('transit', 'In-Transit Location'), ('quarantine', 'Quarantine / Damaged Holding'), ('scrap', 'Scrap / Write-off')], default='main', max_length=20)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary default warehouse for branch/company')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('address', models.TextField(blank=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch this warehouse is physically located in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='core.branch')),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted_set', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'ordering': ['-is_primary', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('posting_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('voucher_type', models.CharField(choices=[('purchase_receipt', 'Goods Received Note (GRN)'), ('purchase_return', 'Goods Returned Note (Purchase Return)'), ('sales_delivery', 'Delivery Note / Sales Dispatch'), ('sales_return', 'Customer Return / Credit Note'), ('pos_sale', 'POS Cashier Sale'), ('stock_transfer_out', 'Inter-Warehouse Transfer Out'), ('stock_transfer_in', 'Inter-Warehouse Transfer In'), ('stock_adjustment', 'Physical Count Adjustment / Write-Off'), ('opening_balance', 'Opening Stock Balance'), ('reversal', 'Reversal Entry')], db_index=True, max_length=30)),
                ('voucher_no', models.CharField(db_index=True, help_text='Document reference (e.g. GRN-0001, INV-0001)', max_length=100)),
                ('voucher_line_id', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Net stock quantity delta. Positive for incoming, negative for outgoing.', max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Cost per unit at the time of movement', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net cost value delta (quantity * unit_cost)', max_digits=16)),
                ('valuation_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Running perpetual weighted average cost after this entry', max_digits=14)),
                ('balance_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Running on-hand stock balance quantity after this entry', max_digits=14)),
                ('balance_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running inventory valuation total value after this entry', max_digits=16)),
                ('batch_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_reversal', models.BooleanField(db_index=True, default=False)),
                ('narration', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='pos.product')),
                ('reversed_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='inventory.stockledgerentry')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'verbose_name_plural': 'Stock Ledger Entries',
                'ordering': ['posting_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockItemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valuation_method', models.CharField(choices=[('weighted_average', 'Moving Weighted Average Cost'), ('fifo', 'First-In, First-Out (FIFO)'), ('standard', 'Standard Costing')], default='weighted_average', max_length=20)),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='If False, sales/dispatches that drive balance below 0 will be rejected')),
                ('reorder_level', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Stock level triggering reorder warnings', max_digits=14)),
                ('reorder_quantity', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Standard batch purchase order quantity', max_digits=14)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_settings', to='pos.product')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_product_settings', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Stock Item Setting',
                'verbose_name_plural': 'Stock Item Settings',
            },
        ),
        migrations.AddField(
            model_name='stockadjustmentdocument',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='ValuationLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('original_quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('remaining_quantity', models.DecimalField(decimal_places=4, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))])),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('is_exhausted', models.BooleanField(db_index=True, default=False)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='pos.product')),
                ('stock_ledger_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='inventory.stockledgerentry')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_layers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Valuation Layer',
                'verbose_name_plural': 'Valuation Layers',
                'ordering': ['received_date', 'created_at'],
                'indexes': [models.Index(fields=['company', 'warehouse', 'product', 'is_exhausted', 'received_date'], name='inventory_v_company_04e8c1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'warehouse', 'product', 'posting_time'], name='inventory_s_company_b2985d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'voucher_type', 'voucher_no'], name='inventory_s_company_b79381_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['company', 'product', 'posting_date'], name='inventory_s_company_c71dbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='inventory_stock_ledger_quantity_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='stockledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_stock_ledger_unit_cost_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitemsettings',
            unique_together={('company', 'product')},
        ),
    ]
