# Generated by Django 4.2.7 on 2026-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Barcode or product code for scanning', max_length=50, null=True, unique=True),
        ),
    ]
