# Generated by Django 4.2.7 on 2026-02-06 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_product_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.IntegerField(default=10, help_text='Alert when stock falls below this level'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.IntegerField(default=0, help_text='Current stock quantity'),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('restock', 'Restock'), ('damage', 'Damage/Loss'), ('return', 'Customer Return'), ('correction', 'Stock Correction'), ('sale', 'Sale')], max_length=20)),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('previous_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='pos.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
