# Generated by Django 5.0.14 on 2026-02-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_purchase_supplier_purchaseitem_purchase_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_alert_days',
            field=models.IntegerField(default=3, help_text='Alert X days before expiry'),
        ),
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Product expiry date (optional)', null=True),
        ),
    ]
