# Generated by Django 5.0.14 on 2026-02-07 06:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_sale_cashier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='My Retail Shop', max_length=200)),
                ('business_address', models.TextField(blank=True)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax/VAT registration number', max_length=50)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16, help_text='VAT/Tax rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('vat_enabled', models.BooleanField(default=True, help_text='Enable VAT calculation')),
                ('receipt_header', models.TextField(blank=True, help_text='Custom header text for receipts')),
                ('receipt_footer', models.TextField(blank=True, help_text='Custom footer text for receipts')),
                ('show_logo_on_receipt', models.BooleanField(default=False)),
                ('currency_symbol', models.CharField(default='KES', max_length=10)),
                ('currency_position', models.CharField(choices=[('before', 'Before Amount'), ('after', 'After Amount')], default='before', max_length=10)),
                ('default_low_stock_threshold', models.IntegerField(default=10)),
                ('enable_low_stock_alerts', models.BooleanField(default=True)),
                ('default_expiry_alert_days', models.IntegerField(default=3)),
                ('enable_expiry_alerts', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=False, help_text='Allow sales when stock is 0')),
                ('require_product_code', models.BooleanField(default=False, help_text='Make product code mandatory')),
                ('auto_generate_product_code', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Settings',
                'verbose_name_plural': 'Business Settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('sale', 'Sale'), ('stock_adjust', 'Stock Adjustment'), ('purchase', 'Purchase'), ('settings', 'Settings Change')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='pos_activit_timesta_3e6269_idx'), models.Index(fields=['user', '-timestamp'], name='pos_activit_user_id_b06c7e_idx')],
            },
        ),
    ]
