# Generated by Django 5.0.14 on 2026-02-07 07:09

import pos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_customer_expensecategory_paymentmethod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Company logo (will be automatically optimized)', null=True, upload_to='business/logos/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (will be automatically optimized)', null=True, upload_to=pos.models.product_image_path),
        ),
    ]
