# Generated by Django 5.0.14 on 2026-02-07 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_businesssettings_logo_product_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lifetime_points',
            field=models.IntegerField(default=0, help_text='Total points earned all time'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='loyalty_points',
            field=models.IntegerField(default=0, help_text='Current available loyalty points'),
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points_required', models.IntegerField(help_text='Points needed to redeem this reward')),
                ('reward_type', models.CharField(choices=[('discount', 'Discount'), ('product', 'Free Product'), ('voucher', 'Voucher')], default='discount', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, help_text='Discount amount in KES', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('max_redemptions', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('redemption_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, help_text='Free product reward', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product')),
            ],
            options={
                'ordering': ['points_required'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_redemptions', to='pos.customer')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.sale')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='pos.loyaltyreward')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('earn', 'Points Earned'), ('redeem', 'Points Redeemed'), ('adjust', 'Manual Adjustment'), ('expire', 'Points Expired'), ('bonus', 'Bonus Points')], max_length=20)),
                ('points', models.IntegerField(help_text='Positive for earning, negative for redemption')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Purchase amount or discount value', max_digits=10)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='pos.customer')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='pos.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
