# Generated by Django 6.0.2 on 2026-02-11 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_supplierpayment_paymentallocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_auto_cut',
            field=models.BooleanField(default=True, help_text='Auto-cut paper after printing'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_copies',
            field=models.IntegerField(default=1, help_text='Number of receipt copies to print'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', help_text='Font size for thermal receipts', max_length=10),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_print_barcode',
            field=models.BooleanField(default=True, help_text='Print barcode on thermal receipts'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_print_logo',
            field=models.BooleanField(default=True, help_text='Print logo on thermal receipts'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_receipt_width',
            field=models.IntegerField(choices=[(58, '58mm'), (80, '80mm')], default=80, help_text='Thermal printer paper width'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='thermal_show_tax_breakdown',
            field=models.BooleanField(default=True, help_text='Show VAT breakdown on receipt'),
        ),
    ]
