# Generated by Django 6.0.2 on 2026-02-12 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_multi_tenancy'),
        ('pos', '0012_businesssettings_thermal_auto_cut_and_more'),
    ]

    operations = [
    ]
