# Generated by Django 6.0.2 on 2026-02-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_fix_paymentmethod_unique'),
        ('pos', '0013_merge_20260212_2005'),
    ]

    operations = [
    ]
