# Generated by Django 6.0.2 on 2026-02-13 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_make_business_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesssettings',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=16, help_text='VAT/Tax rate in percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, help_text='Barcode or product code for scanning', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_number',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('business', 'customer_code')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('business', 'purchase_number')},
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('business', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('business', 'name')},
        ),
    ]
