# Generated by Django 6.0.2 on 2026-02-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_make_phone_required_add_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_code_idx',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price (what customers pay)', max_digits=10),
        ),
    ]
