# Generated by Django 6.0.2 on 2026-02-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_add_unit_of_measurement'),
        ('pos', '0032_remove_customer_pos_customer_phone_idx_and_more'),
    ]

    operations = [
    ]
