# Generated by Django 6.0.2 on 2026-02-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0032_add_license_expiry'),
        ('pos', '0035_assign_loyalty_rewards_to_business'),
    ]

    operations = [
    ]
