# Generated by Django 6.0.2 on 2026-02-14 17:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0036_merge_20260214_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='bulk_unit_name',
            field=models.CharField(blank=True, help_text='Name of bulk unit (e.g., Carton, Box, Sack)', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selling price for one bulk unit', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='How many base units in one bulk unit (e.g., 12 pieces in a carton)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_name',
            field=models.CharField(blank=True, help_text='Name of unit sold (for display)', max_length=50),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_type',
            field=models.CharField(choices=[('base', 'Base Unit'), ('bulk', 'Bulk Unit')], default='base', help_text='Which unit was sold', max_length=10),
        ),
    ]
