# Generated by Django 6.0.2 on 2026-02-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0037_product_bulk_unit_name_product_bulk_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_damaged',
            field=models.PositiveIntegerField(default=0, help_text='Quantity damaged or missing'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_received',
            field=models.PositiveIntegerField(default=0, help_text='Actual quantity received (good items)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='receiving_notes',
            field=models.TextField(blank=True, help_text='Notes about receiving (damage details, etc.)'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity ordered'),
        ),
    ]
