# Generated by Django 6.0.2 on 2026-02-14 18:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0038_purchaseitem_quantity_damaged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReturnedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(editable=False, max_length=20)),
                ('return_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to Supplier'), ('acknowledged', 'Acknowledged by Supplier'), ('collected', 'Goods Collected'), ('credited', 'Credit Note Received'), ('replaced', 'Replacement Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('return_reason', models.CharField(choices=[('damaged', 'Damaged on Delivery'), ('wrong_item', 'Wrong Item Delivered'), ('expired', 'Expired Product'), ('quality', 'Quality Issue'), ('overstock', 'Overstock Return'), ('recall', 'Product Recall'), ('other', 'Other')], max_length=20)),
                ('reason_details', models.TextField(help_text='Detailed explanation of return reason')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credit_note_number', models.CharField(blank=True, help_text='Credit note number from supplier', max_length=50)),
                ('credit_note_date', models.DateField(blank=True, null=True)),
                ('credit_note_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('collection_date', models.DateField(blank=True, help_text='Date goods were collected by supplier', null=True)),
                ('collection_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_returned_notes', to='pos.business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns_created', to=settings.AUTH_USER_MODEL)),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_returned_notes', to='pos.purchase')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_returned_notes', to='pos.supplier')),
            ],
            options={
                'verbose_name': 'Goods Returned Note',
                'verbose_name_plural': 'Goods Returned Notes',
                'ordering': ['-return_date', '-created_at'],
                'unique_together': {('business', 'grn_number')},
            },
        ),
        migrations.CreateModel(
            name='GoodsReturnedNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item_notes', models.TextField(blank=True, help_text='Specific notes about this item')),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.goodsreturnednote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
            ],
        ),
    ]
