# Generated by Django 6.0.2 on 2026-02-15 06:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0042_add_email_system'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_barcode_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='pos_purchase_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='pos_purchase_supplier_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_invoice_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_cashier_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='pos_saleitem_sale_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='pos_saleitem_product_idx',
        ),
        migrations.RemoveIndex(
            model_name='shift',
            name='pos_shift_cashier_idx',
        ),
        migrations.RemoveIndex(
            model_name='shift',
            name='pos_shift_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='pos_supplier_active_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='pos_emaillo_busines_c55ec1_idx',
            old_name='pos_emaillo_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='pos_emaillo_templat_012f57_idx',
            old_name='pos_emaillo_templat_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='pricing_unit_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text="Quantity for pricing unit (e.g., 100 for 'per 100g', 1 for 'per kg')", max_digits=10),
        ),
    ]
