# Generated by Django 6.0.2 on 2026-02-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0045_add_subscription_payments'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='subscriptionpayment',
            new_name='pos_subscri_busines_44cda5_idx',
            old_name='pos_subscri_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='subscriptionpayment',
            new_name='pos_subscri_status_d9fd96_idx',
            old_name='pos_subscri_status_idx',
        ),
        migrations.AlterField(
            model_name='business',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free Trial (30 Days)'), ('basic', 'Basic'), ('professional', 'Professional')], default='free', max_length=50),
        ),
    ]
