# Generated by Django 6.0.2 on 2026-02-16 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0047_simplify_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_enabled',
            field=models.BooleanField(default=True, help_text='Enable loyalty program'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_gold_multiplier',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points multiplier for Gold customers (2.0 = double points)', max_digits=5),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_gold_threshold',
            field=models.DecimalField(decimal_places=2, default=50000, help_text='Lifetime spending to reach Gold tier', max_digits=10),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_max_redeem_percentage',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Maximum percentage of sale that can be paid with points', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_min_points_redeem',
            field=models.IntegerField(default=100, help_text='Minimum points required to redeem'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_platinum_multiplier',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points multiplier for Platinum customers (3.0 = triple points)', max_digits=5),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_platinum_threshold',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='Lifetime spending to reach Platinum tier', max_digits=10),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_points_expire',
            field=models.BooleanField(default=False, help_text='Enable points expiry'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_points_expiry_months',
            field=models.IntegerField(default=12, help_text='Months until points expire (if expiry enabled)'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_points_per_currency',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Amount spent to earn 1 point (e.g., KES 100 = 1 point)', max_digits=10),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_points_value',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Value of 1 point in currency (e.g., 1 point = KES 1)', max_digits=10),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_regular_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Points multiplier for Regular customers (1.0 = normal rate)', max_digits=5),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_silver_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Points multiplier for Silver customers (1.5 = 50% bonus)', max_digits=5),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='loyalty_silver_threshold',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Lifetime spending to reach Silver tier', max_digits=10),
        ),
    ]
