# Generated by Django 6.0.2 on 2026-02-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0050_add_cash_float_management'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashfloat',
            new_name='pos_cashflo_busines_23d611_idx',
            old_name='pos_cashflo_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='cashfloat',
            new_name='pos_cashflo_busines_f4e7d5_idx',
            old_name='pos_cashflo_busines_status_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('sale', 'Sale'), ('stock_adjust', 'Stock Adjustment'), ('purchase', 'Purchase'), ('settings', 'Settings Change'), ('backup', 'Data Backup')], max_length=20),
        ),
    ]
