# Generated by Django 6.0.2 on 2026-02-18 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0051_add_performance_indexes'),
        ('pos', '0051_rename_pos_cashflo_busines_idx_pos_cashflo_busines_23d611_idx_and_more'),
    ]

    operations = [
    ]
