# Generated by Django 6.0.2 on 2026-02-19 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0053_add_purchase_cancellation_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='theme_accent',
            field=models.CharField(default='#cd8a4c', help_text='Accent color for highlights (hex code, e.g., #cd8a4c)', max_length=7),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='theme_dark',
            field=models.CharField(default='#1a1514', help_text='Dark color for sidebar/headers (hex code, e.g., #1a1514)', max_length=7),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='theme_light',
            field=models.CharField(default='#d5d3d4', help_text='Light color for text/backgrounds (hex code, e.g., #d5d3d4)', max_length=7),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='theme_primary',
            field=models.CharField(default='#224195', help_text='Primary brand color (hex code, e.g., #224195)', max_length=7),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode for scanning (EAN, UPC, etc.)', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
