# Generated by Django 6.0.2 on 2026-02-21 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0058_fix_activitylog_index_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClosureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(help_text='Date of the closure')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, help_text='Opening cash/floats', max_digits=12)),
                ('cash_sales', models.DecimalField(decimal_places=2, help_text='Total cash sales for the day', max_digits=12)),
                ('expected_cash', models.DecimalField(decimal_places=2, help_text='Opening + Cash sales', max_digits=12)),
                ('declared_cash', models.DecimalField(decimal_places=2, help_text='Cash declared by cashier (blind)', max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, help_text='Declared - Expected', max_digits=12)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shifts_closed', models.IntegerField(default=0, help_text='Number of shifts closed')),
                ('floats_reconciled', models.IntegerField(default=0, help_text='Number of cash floats reconciled')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Day Closure Report',
                'verbose_name_plural': 'Day Closure Reports',
                'ordering': ['-report_date', '-closed_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='pos_actlog_bus_ent_idx',
            old_name='pos_activitylog_bus_ent_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='pos_actlog_corr_idx',
            old_name='pos_activitylog_corr_idx',
        ),
        migrations.AlterField(
            model_name='idempotencykey',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_keys', to='pos.business'),
        ),
        migrations.AddField(
            model_name='dayclosurereport',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_closures', to='pos.business'),
        ),
        migrations.AddField(
            model_name='dayclosurereport',
            name='closed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_closures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dayclosurereport',
            index=models.Index(fields=['business', 'report_date'], name='pos_dayclos_busines_549aea_idx'),
        ),
        migrations.AddIndex(
            model_name='dayclosurereport',
            index=models.Index(fields=['business', '-closed_at'], name='pos_dayclos_busines_18f492_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayclosurereport',
            unique_together={('business', 'report_date')},
        ),
    ]
