# Generated by Django 6.0.2 on 2026-02-25 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0060_add_support_access_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Locked after Z-Report generation'),
        ),
        migrations.AddField(
            model_name='sale',
            name='locked_at',
            field=models.DateTimeField(blank=True, help_text='When this sale was locked', null=True),
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Sequential number per business')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, help_text='Starting cash in drawer', max_digits=12)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this session')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='pos.business')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'POS Session',
                'verbose_name_plural': 'POS Sessions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddField(
            model_name='sale',
            name='session',
            field=models.ForeignKey(blank=True, help_text='POS session this sale belongs to', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='pos.possession'),
        ),
        migrations.CreateModel(
            name='ZReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('z_number', models.IntegerField(editable=False, help_text='Sequential Z-Report number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(editable=False, help_text='Complete immutable financial snapshot')),
                ('data_hash', models.CharField(editable=False, help_text='SHA256 hash of report_data', max_length=64)),
                ('is_voided', models.BooleanField(db_index=True, default=False)),
                ('voided_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('void_reason', models.TextField(blank=True, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='z_reports', to='pos.business')),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='z_reports_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='z_report', to='pos.possession')),
                ('voided_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='z_reports_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Z-Report',
                'verbose_name_plural': 'Z-Reports',
                'ordering': ['-created_at'],
                'permissions': [('can_close_session', 'Can close POS session and generate Z-Report'), ('can_void_zreport', 'Can void Z-Report'), ('can_export_zreport', 'Can export Z-Report'), ('can_verify_zreport', 'Can verify Z-Report integrity')],
            },
        ),
        migrations.CreateModel(
            name='ZReportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('viewed', 'Viewed'), ('exported_pdf', 'Exported PDF'), ('exported_csv', 'Exported CSV'), ('exported_json', 'Exported JSON'), ('voided', 'Voided'), ('integrity_verified', 'Integrity Verified'), ('integrity_failed', 'Integrity Check Failed'), ('printed', 'Printed')], db_index=True, max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zreport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='pos.zreport')),
            ],
            options={
                'verbose_name': 'Z-Report Audit Log',
                'verbose_name_plural': 'Z-Report Audit Logs',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['business', 'status'], name='pos_possess_busines_c3a623_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['business', 'opened_at'], name='pos_possess_busines_77350a_idx'),
        ),
        migrations.AddIndex(
            model_name='possession',
            index=models.Index(fields=['status', 'opened_at'], name='pos_possess_status_ecb2c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'open'), models.Q(('status', 'closed'), ('closed_at__isnull', False)), _connector='OR'), name='pos_session_closed_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash__gte', 0)), name='pos_session_opening_cash_non_negative'),
        ),
        migrations.AlterUniqueTogether(
            name='possession',
            unique_together={('business', 'session_number')},
        ),
        migrations.AddIndex(
            model_name='zreport',
            index=models.Index(fields=['business', 'z_number'], name='pos_zreport_busines_e70b18_idx'),
        ),
        migrations.AddIndex(
            model_name='zreport',
            index=models.Index(fields=['business', 'created_at'], name='pos_zreport_busines_eff95f_idx'),
        ),
        migrations.AddIndex(
            model_name='zreport',
            index=models.Index(fields=['is_voided'], name='pos_zreport_is_void_220907_idx'),
        ),
        migrations.AddIndex(
            model_name='zreport',
            index=models.Index(fields=['business', 'is_voided', 'created_at'], name='pos_zreport_busines_d88709_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zreport',
            unique_together={('business', 'z_number')},
        ),
        migrations.AddIndex(
            model_name='zreportauditlog',
            index=models.Index(fields=['zreport', 'performed_at'], name='pos_zreport_zreport_3ae6f8_idx'),
        ),
        migrations.AddIndex(
            model_name='zreportauditlog',
            index=models.Index(fields=['performed_by', 'performed_at'], name='pos_zreport_perform_be53f2_idx'),
        ),
        migrations.AddIndex(
            model_name='zreportauditlog',
            index=models.Index(fields=['action', 'performed_at'], name='pos_zreport_action_1dd752_idx'),
        ),
    ]
