# Generated by Django 6.0.2 on 2026-03-01 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0062_add_kenyan_tax_compliance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='business',
            name='pos_business_cu_number_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_hs_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_tims_sync_idx',
        ),
    ]
