# Generated by Django 6.0.2 on 2026-03-10 18:37

from django.db import migrations


def set_default_blocked_domains(apps, schema_editor):
    """Set default list of blocked disposable email domains"""
    RegistrationSettings = apps.get_model('pos', 'RegistrationSettings')
    
    # Common disposable email domains to block
    blocked_domains = [
        'tempmail.com', 'guerrillamail.com', '10minutemail.com', 'mailinator.com',
        'throwaway.email', 'temp-mail.org', 'fakeinbox.com', 'trashmail.com',
        'yopmail.com', 'maildrop.cc', 'getnada.com', 'emailondeck.com',
        'sharklasers.com', 'grr.la', 'discard.email', 'spamgourmet.com'
    ]
    
    # Get or create settings
    settings, created = RegistrationSettings.objects.get_or_create(pk=1)
    
    # Only set if not already configured
    if not settings.blocked_email_domains:
        settings.blocked_email_domains = ', '.join(blocked_domains)
        settings.save()


def reverse_func(apps, schema_editor):
    """Reverse migration - clear blocked domains"""
    RegistrationSettings = apps.get_model('pos', 'RegistrationSettings')
    try:
        settings = RegistrationSettings.objects.get(pk=1)
        settings.blocked_email_domains = ''
        settings.save()
    except RegistrationSettings.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0064_add_registration_control'),
    ]

    operations = [
        migrations.RunPython(set_default_blocked_domains, reverse_func),
    ]
