# Generated by Django 6.0.2 on 2026-03-22 12:18

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0065_set_default_blocked_domains'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceivedNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(editable=False, max_length=20)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('discrepancy', 'Discrepancy Noted')], default='confirmed', max_length=20)),
                ('delivery_note_number', models.CharField(blank=True, help_text='Supplier delivery note / waybill number', max_length=100)),
                ('vehicle_number', models.CharField(blank=True, max_length=50)),
                ('driver_name', models.CharField(blank=True, max_length=100)),
                ('total_ordered_qty', models.PositiveIntegerField(default=0)),
                ('total_received_qty', models.PositiveIntegerField(default=0)),
                ('total_damaged_qty', models.PositiveIntegerField(default=0)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Goods Received Note',
                'verbose_name_plural': 'Goods Received Notes',
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceivedNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField()),
                ('quantity_damaged', models.PositiveIntegerField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='businessregistration',
            new_name='pos_busines_status_916166_idx',
            old_name='pos_busreg_status_idx',
        ),
        migrations.RenameIndex(
            model_name='businessregistration',
            new_name='pos_busines_email_fb1bdb_idx',
            old_name='pos_busreg_email_idx',
        ),
        migrations.RenameIndex(
            model_name='invitationcode',
            new_name='pos_invitat_code_ec5edb_idx',
            old_name='pos_invitat_code_act_idx',
        ),
        migrations.RenameIndex(
            model_name='invitationcode',
            new_name='pos_invitat_valid_u_fd0bfa_idx',
            old_name='pos_invitat_valid_idx',
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='allowed_email_domains',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed email domains (e.g., company.com, partner.co.ke)'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='admin_notification_emails',
            field=models.TextField(blank=True, help_text='Comma-separated list of admin emails for notifications'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='allowed_email_domains',
            field=models.TextField(blank=True, help_text='If set, only these domains are allowed (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='blocked_email_domains',
            field=models.TextField(blank=True, help_text='Comma-separated list of blocked email domains (e.g., tempmail.com, guerrillamail.com)'),
        ),
        migrations.AlterField(
            model_name='registrationsettings',
            name='registration_closed_message',
            field=models.TextField(blank=True, default='Registration is currently closed. Please contact support for access.', help_text='Message shown when registration is disabled'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_received_notes', to='pos.business'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='purchase',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_note', to='pos.purchase'),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceivednote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_received_notes', to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='grn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='goodsreceivednoteitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceivednote',
            unique_together={('business', 'grn_number')},
        ),
    ]
