# Generated by Django 6.0.2 on 2026-03-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0067_enhance_purchase_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Product description'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active products appear in POS and reports'),
        ),
        migrations.AddField(
            model_name='product',
            name='lead_time_days',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Expected lead time from supplier in days'),
        ),
        migrations.AddField(
            model_name='product',
            name='minimum_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed selling price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, help_text='Default supplier for reordering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_products', to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('stock', 'Stock Product'), ('service', 'Service (No Inventory)'), ('variant', 'Variant Product'), ('bundle', 'Bundle / Combo'), ('weighted', 'Weighted (kg/L)'), ('serialized', 'Serialized (IMEI/Serial)'), ('batch', 'Batch / Expiry Tracked')], default='stock', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, help_text='Suggested reorder quantity', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Wholesale / bulk customer price', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='pos.business')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.brand'),
        ),
    ]
