# Generated by Django 6.0.2 on 2026-03-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0068_enhance_product_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Per-item note (e.g. no onions, gift wrap)', max_length=255),
        ),
    ]
