# Generated by Django 5.2.12 on 2026-03-24 17:05

from django.db import migrations, models
from django.core.validators import MinValueValidator
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0074_saleitem_cost_price_at_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[MinValueValidator(Decimal('0.001'))]),
        ),
    ]
