# Generated by Django 5.2.12 on 2026-03-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0081_branch_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_bus_phone_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_bus_tier_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='pos_customer_bus_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_bus_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_bus_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_bus_barcode_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_bus_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='pos_product_bus_cat_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='pos_purchase_bus_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='pos_purchase_bus_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_bus_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_bus_cashier_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='pos_sale_bus_customer_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockadjustment',
            name='pos_stockadj_bus_prod_dt_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockadjustment',
            name='pos_stockadj_bus_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='branchstock',
            new_name='pos_branchs_branch__c3f80b_idx',
            old_name='pos_branchs_branch__idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='pos_stocktr_busines_6be3c2_idx',
            old_name='pos_stocktr_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='pos_stocktr_source__a6fdf2_idx',
            old_name='pos_stocktr_source__idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransfer',
            new_name='pos_stocktr_destina_545ccf_idx',
            old_name='pos_stocktr_dest___idx',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='message',
            field=models.TextField(help_text='Campaign message body'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, help_text='Email subject line', max_length=300),
        ),
        migrations.AlterField(
            model_name='customerpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='criteria_value',
            field=models.CharField(blank=True, help_text='e.g. tier name or threshold', max_length=100),
        ),
        migrations.AlterField(
            model_name='customersegment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='pos.expensecategory'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='events',
            field=models.JSONField(default=list, help_text='List of subscribed event types'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='webhookdelivery',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('business', 'expense_number')},
        ),
    ]
