# Generated by Django 5.2.12 on 2026-03-29 05:08

from django.db import migrations, models
import django.db.models.deletion


def backfill_expense_business(apps, schema_editor):
    Expense = apps.get_model('pos', 'Expense')
    for expense in Expense.objects.filter(business__isnull=True).select_related('category'):
        if expense.category and expense.category.business_id:
            expense.business_id = expense.category.business_id
            expense.save(update_fields=['business_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0081_branch_models'),
    ]

    operations = [
        migrations.RunPython(backfill_expense_business, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='expense',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='pos.business'),
        ),
    ]
