# Generated by Django 5.2.12 on 2026-04-04 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0082_backfill_expense_business'),
        ('pos', '0083_bulk_advanced_fields'),
    ]

    operations = [
    ]
