# Generated by Django 5.2.12 on 2026-04-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0085_user_management_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('damage', 'Damage/Loss'), ('expired', 'Expired Items'), ('return', 'Customer Return'), ('correction', 'Stock Correction'), ('sale', 'Sale'), ('bulk_break', 'Bulk Break')], max_length=20),
        ),
    ]
