# Generated by Django 5.1.4 on 2026-04-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0092_businesssettings_overtime_multiplier'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='pos_backupa_user_id_701887_idx',
            old_name='pos_backupa_user_id_f4c3a1_idx',
        ),
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='pos_backupa_busines_6ae6d3_idx',
            old_name='pos_backupa_business_f4c3a1_idx',
        ),
        migrations.RenameIndex(
            model_name='backupauditlog',
            new_name='pos_backupa_status_e3180a_idx',
            old_name='pos_backupa_status_f4c3a1_idx',
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('sale', 'Sale'), ('refund', 'Refund'), ('stock_adjust', 'Stock Adjustment'), ('purchase', 'Purchase'), ('settings', 'Settings Change'), ('backup', 'Data Backup'), ('restore', 'Data Restore'), ('export', 'Export'), ('password_change', 'Password Change')], max_length=20),
        ),
    ]
