# Generated by Django 5.1.4 on 2026-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0093_activity_log_new_action_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='mpesa_account_name',
            field=models.CharField(blank=True, help_text='Account name shown to customers (for Paybill)', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='mpesa_account_reference',
            field=models.CharField(blank=True, help_text='Default account reference / prompt shown to cashier (e.g. invoice number)', max_length=100),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='mpesa_enabled',
            field=models.BooleanField(default=False, help_text='Show M-Pesa payment details on POS and receipts'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='mpesa_shortcode',
            field=models.CharField(blank=True, help_text='Paybill number or Till number', max_length=20),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='mpesa_type',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Buy Goods (Till)')], default='paybill', help_text='Type of M-Pesa number', max_length=10),
        ),
    ]
