# Generated by Django 5.1.4 on 2026-04-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0094_mpesa_config_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='M-Pesa phone number for Send Money (e.g. 0712345678)', max_length=20),
        ),
        migrations.AlterField(
            model_name='businesssettings',
            name='mpesa_type',
            field=models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Buy Goods (Till)'), ('phone', 'Phone Number (Send Money)')], default='paybill', help_text='Type of M-Pesa number', max_length=10),
        ),
    ]
