# Generated by Django 5.1.4 on 2026-04-16 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0096_backfill_mpesa_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotion',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='promotion',
            name='applies_to',
            field=models.CharField(choices=[('cart', 'Entire Cart'), ('products', 'Specific Products'), ('category', 'Specific Category')], default='cart', max_length=10),
        ),
        migrations.AddField(
            model_name='promotion',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='pos.business'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotion',
            name='happy_hour_end',
            field=models.TimeField(blank=True, help_text='Daily end time for happy hour (e.g. 19:00)', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='happy_hour_start',
            field=models.TimeField(blank=True, help_text='Daily start time for happy hour (e.g. 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed', 'Fixed Amount Off'), ('buy_x_get_y', 'Buy X Get Y Free'), ('price_cut', 'Price Cut (Fixed Price)'), ('bundle', 'Bundle Deal'), ('happy_hour', 'Happy Hour')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='pos.category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='promotions', to='pos.product'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='buy_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Buy this many (BOGO: 1)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(blank=True, help_text='Optional promo code cashier/customer can enter. Leave blank for auto-apply.', max_length=50),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='% for percentage; KES amount for fixed; new price for price_cut; total for bundle', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='get_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Get this many free (BOGO: 1)'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='max_uses',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart total to qualify (0 = no minimum)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('code__gt', '')), fields=('business', 'code'), name='unique_promo_code_per_business'),
        ),
    ]
