# Generated by Django 5.1.4 on 2026-04-25 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0097_promotions_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='HSCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Full HS code e.g. 0901.21 or 090121', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Official WCO/KRA description', max_length=500)),
                ('chapter', models.CharField(db_index=True, help_text='2-digit chapter e.g. 09', max_length=2)),
                ('heading', models.CharField(db_index=True, help_text='4-digit heading e.g. 0901', max_length=4)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=16, help_text='Standard VAT rate for this code (%)', max_digits=5)),
                ('excise_rate', models.DecimalField(decimal_places=2, default=0, help_text='Excise duty rate (%)', max_digits=5)),
                ('import_duty', models.DecimalField(decimal_places=2, default=0, help_text='Import duty rate (%)', max_digits=5)),
                ('is_excisable', models.BooleanField(default=False)),
                ('unit', models.CharField(blank=True, choices=[('kg', 'Kilogram (kg)'), ('g', 'Gram (g)'), ('l', 'Litre (l)'), ('ml', 'Millilitre (ml)'), ('m', 'Metre (m)'), ('m2', 'Square Metre (m²)'), ('m3', 'Cubic Metre (m³)'), ('pcs', 'Pieces (pcs)'), ('doz', 'Dozen'), ('u', 'Unit'), ('t', 'Tonne (t)'), ('', 'No unit')], default='', help_text='Standard unit of quantity', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes, KRA-specific guidance')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HS Code',
                'verbose_name_plural': 'HS Codes',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['chapter'], name='pos_hscode_chapter_c4aa08_idx'), models.Index(fields=['heading'], name='pos_hscode_heading_73b763_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='hs_code_ref',
            field=models.ForeignKey(blank=True, help_text='Link to the HS Code library entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.hscode'),
        ),
    ]
