# Generated by Django 6.0.2 on 2026-08-11 18:30

import django.db.models.deletion
import pos.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0098_hscode_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique VAT code identifier (e.g., VAT-STD, VAT-ZERO, VAT-EXEMPT)', max_length=20)),
                ('name', models.CharField(help_text="Descriptive name (e.g., 'Standard Rated (16%)')", max_length=100)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('16.00'), help_text='VAT rate as percentage (e.g., 16.00 for 16%)', max_digits=5)),
                ('description', models.TextField(blank=True, help_text='Additional details about when this VAT code applies')),
                ('hs_code_chapter', models.CharField(blank=True, help_text="HS Code chapter (2-digit) this VAT code typically applies to (e.g., '09')", max_length=2, null=True)),
                ('excise_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Excise duty rate percentage (if applicable)', max_digits=5)),
                ('is_excisable', models.BooleanField(default=False, help_text='Whether products with this VAT code are subject to excise duty')),
                ('import_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Import duty rate percentage (if applicable)', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive VAT codes cannot be assigned to new products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='Business/tenant this VAT code belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='vat_codes', to='pos.business')),
            ],
            options={
                'verbose_name': 'VAT Code',
                'verbose_name_plural': 'VAT Codes',
                'ordering': ['code'],
            },
            bases=(pos.models.CacheInvalidationMixin, pos.models.AuditModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_code',
            field=models.ForeignKey(blank=True, help_text='VAT Code for tax treatment (if not set, uses tax_class)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.vatcode'),
        ),
        migrations.AddIndex(
            model_name='vatcode',
            index=models.Index(fields=['business', 'is_active'], name='pos_vatcode_busines_9cf31d_idx'),
        ),
        migrations.AddIndex(
            model_name='vatcode',
            index=models.Index(fields=['business', 'vat_rate'], name='pos_vatcode_busines_6d4a53_idx'),
        ),
        migrations.AddIndex(
            model_name='vatcode',
            index=models.Index(fields=['business', 'hs_code_chapter'], name='pos_vatcode_busines_b837e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vatcode',
            unique_together={('business', 'code')},
        ),
    ]
