# Generated by Django 5.1.4 on 2026-09-11 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0099_add_vat_code_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='possession',
            name='cash_difference',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Difference between expected and counted cash', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashier_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='possession',
            name='closing_cash',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Counted cash at close', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal_identifier',
            field=models.CharField(blank=True, help_text='Snapshot of terminal identifier/code', max_length=128),
        ),
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Terminal display name (e.g. Counter 1)', max_length=100)),
                ('terminal_code', models.CharField(help_text='Unique terminal code (e.g. TERM-01)', max_length=50)),
                ('device_token', models.CharField(db_index=True, help_text='Unique device cookie / token identifier', max_length=128, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_cashiers', models.ManyToManyField(blank=True, help_text='Optional: restrict to specific cashiers. If empty, any cashier assigned to this branch can log in.', related_name='assigned_terminals', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='pos.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='pos.business')),
            ],
            options={
                'ordering': ['branch', 'terminal_code'],
            },
        ),
        migrations.CreateModel(
            name='PINLoginAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('terminal_code', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed_pin', 'Incorrect PIN'), ('locked_out', 'Account Locked'), ('invalid_terminal', 'Invalid / Unregistered Terminal'), ('terminal_inactive', 'Terminal Inactive'), ('no_pin_set', 'No PIN Configured'), ('unauthorized_branch', 'Unauthorized Branch'), ('session_closed', 'Session Closed')], db_index=True, max_length=30)),
                ('failure_reason', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_audit_logs', to='pos.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pin_audit_logs', to='pos.business')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_audit_logs', to='pos.posterminal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='possession',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='pos.posterminal'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['business', 'device_token'], name='pos_posterm_busines_f815fd_idx'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['branch', 'is_active'], name='pos_posterm_branch__cb7ad3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='posterminal',
            unique_together={('business', 'terminal_code')},
        ),
        migrations.AddIndex(
            model_name='pinloginauditlog',
            index=models.Index(fields=['business', '-created_at'], name='pos_pinlogi_busines_684eac_idx'),
        ),
        migrations.AddIndex(
            model_name='pinloginauditlog',
            index=models.Index(fields=['branch', '-created_at'], name='pos_pinlogi_branch__d6e8d5_idx'),
        ),
        migrations.AddIndex(
            model_name='pinloginauditlog',
            index=models.Index(fields=['status', '-created_at'], name='pos_pinlogi_status_b5197a_idx'),
        ),
    ]
