# Generated by Django 5.1.4 on 2026-09-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0100_possession_cash_difference_possession_cashier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='cu_number',
            field=models.CharField(blank=True, help_text='Branch Control Unit Number (e.g., KRAMW0012345)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='cu_serial_number',
            field=models.CharField(blank=True, help_text='Branch CU Device / VSCU Serial Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='kra_branch_id',
            field=models.CharField(blank=True, default='00', help_text='KRA eTIMS Branch ID (e.g. 00 for HQ, 01 for Branch 1, 02 for Branch 2)', max_length=10),
        ),
        migrations.AddField(
            model_name='branch',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='Branch-specific KRA PIN (defaults to business KRA PIN if blank)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='tims_enabled',
            field=models.BooleanField(default=False, help_text='Enable KRA TIMS/eTIMS invoice signing for this branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='tims_middleware_url',
            field=models.CharField(blank=True, help_text='Local/LAN endpoint for TIMS middleware (e.g. http://192.168.1.150:8080)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='cu_number',
            field=models.CharField(blank=True, help_text='Override CU Number for this terminal if using dedicated physical ESD', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='cu_serial_number',
            field=models.CharField(blank=True, help_text='Override CU Serial Number for this terminal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='tims_middleware_url',
            field=models.CharField(blank=True, help_text='Override TIMS Middleware URL for this terminal', max_length=255, null=True),
        ),
    ]
