# Generated by Django on 2026-09-12

from django.db import migrations


def backfill_print_receipt_permissions(apps, schema_editor):
    BusinessMembership = apps.get_model('pos', 'BusinessMembership')

    role_required_perms = {
        'owner': ['can_create_sale', 'can_print_receipt', 'can_refund_sale', 'can_void_sale', 'can_edit_price', 'can_view_cost_price', 'can_apply_discount', 'can_exceed_max_discount', 'can_manage_users', 'can_view_reports', 'can_manage_stock'],
        'admin': ['can_create_sale', 'can_print_receipt', 'can_refund_sale', 'can_void_sale', 'can_edit_price', 'can_view_cost_price', 'can_apply_discount', 'can_exceed_max_discount', 'can_manage_users', 'can_view_reports', 'can_manage_stock'],
        'manager': ['can_create_sale', 'can_print_receipt'],
        'cashier': ['can_create_sale', 'can_print_receipt'],
        'sales': ['can_create_sale', 'can_print_receipt'],
    }

    for membership in BusinessMembership.objects.all():
        needed = role_required_perms.get(membership.role, [])
        if needed:
            current_perms = set(membership.permissions or [])
            updated = False
            for p in needed:
                if p not in current_perms:
                    current_perms.add(p)
                    updated = True
            if updated:
                membership.permissions = list(current_perms)
                membership.save(update_fields=['permissions'])


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0101_branch_cu_number_branch_cu_serial_number_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_print_receipt_permissions, reverse_code=migrations.RunPython.noop),
    ]
