# Generated by Django 5.1.4 on 2026-09-12 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0103_unified_multi_branch_stock_ledger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='pos_dispatc_busines_4a35e4_idx',
            old_name='pos_dispatch_bus_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='pos_dispatc_source__bed963_idx',
            old_name='pos_dispatch_src_st_idx',
        ),
        migrations.RenameIndex(
            model_name='dispatch',
            new_name='pos_dispatc_destina_aeb0bd_idx',
            old_name='pos_dispatch_dst_st_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='pos_stockmo_busines_d00711_idx',
            old_name='pos_stockmv_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='pos_stockmo_branch__ffa815_idx',
            old_name='pos_stockmv_branch_p_idx',
        ),
        migrations.RenameIndex(
            model_name='stockmovement',
            new_name='pos_stockmo_movemen_f5b25b_idx',
            old_name='pos_stockmv_movtype_idx',
        ),
        migrations.RenameIndex(
            model_name='stockrequisition',
            new_name='pos_stockre_busines_2530ae_idx',
            old_name='pos_stockrq_busines_idx',
        ),
        migrations.RenameIndex(
            model_name='stockrequisition',
            new_name='pos_stockre_request_5d065e_idx',
            old_name='pos_stockrq_branch_s_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferrequest',
            new_name='pos_stocktr_busines_bc5492_idx',
            old_name='pos_stocktr_busreq_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferrequest',
            new_name='pos_stocktr_source__5368ec_idx',
            old_name='pos_stocktr_src_st_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransferrequest',
            new_name='pos_stocktr_destina_ac95f0_idx',
            old_name='pos_stocktr_dst_st_idx',
        ),
        migrations.AddField(
            model_name='posterminal',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful bidirectional sync', null=True),
        ),
        migrations.AddField(
            model_name='posterminal',
            name='sync_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('synced', 'Synced'), ('error', 'Error')], default='idle', help_text='Current or last known sync status', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='client_created_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when sale was recorded locally on terminal', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generated UUID for offline sync idempotency', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_offline_sync',
            field=models.BooleanField(default=False, help_text='True if recorded offline and synced later'),
        ),
        migrations.AddField(
            model_name='sale',
            name='terminal',
            field=models.ForeignKey(blank=True, help_text='POS Terminal that originated this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.posterminal'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='pos.posterminal'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('business', 'idempotency_key'), name='unique_business_sale_idempotency_key'),
        ),
    ]
