# Generated by Django 5.1.4 on 2026-09-14 20:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0104_pos_terminal_sync_and_idempotency'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransferitem',
            name='discrepancy_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='discrepancy_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='discrepancy_resolution',
            field=models.CharField(blank=True, choices=[('writeoff_loss', 'Write-off as Transit Loss'), ('returned_to_source', 'Return to Source Branch'), ('accepted_variance', 'Accepted Variance / Adjustment')], max_length=30),
        ),
        migrations.AddField(
            model_name='stocktransferitem',
            name='unit_cost_at_dispatch',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Moving avg unit cost at source branch when dispatched', max_digits=12),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='auto_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='discrepancy_resolution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='discrepancy_resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='discrepancy_resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_discrepancy_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='requires_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stocktransferrequest',
            name='total_estimated_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('sale_return', 'Sale Return'), ('purchase_in', 'Purchase / GRN In'), ('supplier_return_out', 'Supplier Return Out'), ('hq_dispatch_out', 'HQ Dispatch Out'), ('branch_receipt_in', 'Branch Receipt In'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('in_transit_out', 'In Transit Out (Dispatched)'), ('transit_loss_writeoff', 'Transit Loss Write-off'), ('transit_return_in', 'Transit Return In'), ('manual_adjustment', 'Manual Adjustment'), ('damage_writeoff', 'Damage Write-off'), ('expiry_writeoff', 'Expiry Write-off'), ('initial_count', 'Initial Stock Count')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stocktransferrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('dispatched', 'In Transit / Dispatched'), ('receiving', 'Receiving in Progress'), ('partially_received', 'Partially Received'), ('discrepancy_flagged', 'Discrepancy Flagged'), ('resolved', 'Discrepancy Resolved'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_approval', max_length=25),
        ),
        migrations.CreateModel(
            name='TransferApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Transfer Policy', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_approve_below_threshold', models.BooleanField(default=False, help_text='If True, transfers with total value <= min_value_threshold auto-approve immediately')),
                ('min_value_threshold', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Transfers exceeding this monetary value require explicit manager approval', max_digits=12)),
                ('min_quantity_threshold', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Transfers exceeding this total unit count require explicit approval', max_digits=10)),
                ('requires_hq_approval', models.BooleanField(default=False, help_text='If True, transfers require HQ admin sign-off even for peer branch transfers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_approval_rules', to='pos.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransferEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('event_type', models.CharField(choices=[('created', 'Created Draft / Request'), ('submitted', 'Submitted for Approval'), ('auto_approved', 'Auto-Approved by Rule'), ('approved', 'Approved by Authorizer'), ('rejected', 'Rejected'), ('dispatched', 'Dispatched / In Transit'), ('received_full', 'Fully Received'), ('received_partial', 'Partially Received (Discrepancy Flagged)'), ('discrepancy_resolved', 'Discrepancy Resolved'), ('cancelled', 'Cancelled'), ('note_added', 'Audit Note Added')], db_index=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_events', to='pos.business')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pos.dispatch')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_events_performed', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pos.stockrequisition')),
                ('transfer_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pos.stocktransferrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['business', '-created_at'], name='pos_transfe_busines_647e1d_idx'), models.Index(fields=['transfer_request', 'created_at'], name='pos_transfe_transfe_aaec4a_idx'), models.Index(fields=['dispatch', 'created_at'], name='pos_transfe_dispatc_ca2236_idx')],
            },
        ),
    ]
