# Generated by Django 5.1.4 on 2026-09-14 21:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0105_stocktransferitem_discrepancy_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierAssignmentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('transfer_requested', 'Transfer Requested'), ('transfer_approved', 'Transfer Approved'), ('transfer_rejected', 'Transfer Rejected'), ('transfer_cancelled', 'Transfer Cancelled'), ('transfer_expired', 'Temporary Transfer Expired (Reverted)'), ('till_assigned', 'Till Scheduled / Assigned'), ('till_activated', 'Till Activated (Shift Started)'), ('till_released', 'Till Released (Shift Ended)'), ('conflict_prevented', 'Schedule Conflict Prevented')], db_index=True, max_length=40)),
                ('reason', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CashierTillAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.DateTimeField(db_index=True, help_text='Scheduled shift start time')),
                ('shift_end', models.DateTimeField(db_index=True, help_text='Scheduled shift end time')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Timestamp when cashier clocked in / opened till', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Timestamp when cashier clocked out / released till', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active (Shift In Progress)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hourly labor rate in KES', max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='CashierTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('permanent', 'Permanent Transfer'), ('temporary', 'Temporary Transfer')], default='temporary', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, help_text='End date required for temporary transfers', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('action_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(help_text='Reason for transfer')),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='posterminal',
            name='operational_status',
            field=models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('offline', 'Offline'), ('maintenance', 'Maintenance')], default='available', help_text='Real-time till operational status', max_length=20),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['branch', 'operational_status'], name='pos_posterm_branch__0aeed4_idx'),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_audit_logs', to='pos.business'),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='from_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_assignment_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.posterminal'),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='to_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='cashiertillassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiertillassignment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_assignments', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='cashiertillassignment',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_assignments', to='pos.business'),
        ),
        migrations.AddField(
            model_name='cashiertillassignment',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiertillassignment',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='till_assignments', to='pos.posterminal'),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.cashiertillassignment'),
        ),
        migrations.AddField(
            model_name='cashiertransferrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cashier_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiertransferrequest',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_transfers', to='pos.business'),
        ),
        migrations.AddField(
            model_name='cashiertransferrequest',
            name='cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiertransferrequest',
            name='from_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_transfers_out', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='cashiertransferrequest',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_cashier_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiertransferrequest',
            name='to_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_transfers_in', to='pos.branch'),
        ),
        migrations.AddField(
            model_name='cashierassignmentauditlog',
            name='transfer_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.cashiertransferrequest'),
        ),
        migrations.AddIndex(
            model_name='cashiertillassignment',
            index=models.Index(fields=['business', 'branch', 'status'], name='pos_cashier_busines_14290a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiertillassignment',
            index=models.Index(fields=['cashier', 'status', 'shift_start'], name='pos_cashier_cashier_37da03_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiertillassignment',
            index=models.Index(fields=['terminal', 'status', 'shift_start'], name='pos_cashier_termina_44da99_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiertransferrequest',
            index=models.Index(fields=['business', 'status'], name='pos_cashier_busines_b28a66_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiertransferrequest',
            index=models.Index(fields=['to_branch', 'status'], name='pos_cashier_to_bran_30b80b_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiertransferrequest',
            index=models.Index(fields=['from_branch', 'status'], name='pos_cashier_from_br_403bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='cashiertransferrequest',
            index=models.Index(fields=['cashier', 'status'], name='pos_cashier_cashier_8cfc64_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierassignmentauditlog',
            index=models.Index(fields=['business', '-timestamp'], name='pos_cashier_busines_2f0788_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierassignmentauditlog',
            index=models.Index(fields=['cashier', '-timestamp'], name='pos_cashier_cashier_d2315c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashierassignmentauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='pos_cashier_action_cfcb08_idx'),
        ),
    ]
