# Generated by Django 5.1.4 on 2026-09-16 02:53

import django.db.models.deletion
import pos.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0106_cashierassignmentauditlog_cashiertillassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(help_text='e.g. KCB Bank, Equity Bank, Co-operative Bank, Absa, MPESA Paybill/Till', max_length=100)),
                ('account_name', models.CharField(help_text='e.g. Main Operations Account, CBD Collection Till Account', max_length=150)),
                ('account_number', models.CharField(help_text='Bank Account Number or Paybill/Till Number', max_length=60)),
                ('branch_name', models.CharField(blank=True, help_text='Bank branch / location', max_length=100)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial ledger balance before tracking in system', max_digits=14)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current calculated book balance', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default bank account pre-selected for physical deposits')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='pos.business')),
            ],
            options={
                'ordering': ['-is_default', 'bank_name', 'account_name'],
            },
            bases=(pos.models.CacheInvalidationMixin, pos.models.AuditModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('period_start', models.DateField(help_text='Collection period start date')),
                ('period_end', models.DateField(help_text='Collection period end date')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='System-calculated collections due to be banked', max_digits=14)),
                ('deposited_amount', models.DecimalField(decimal_places=2, help_text='Actual physical amount on the bank deposit slip', max_digits=14)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='deposited_amount - expected_amount (Negative = Short-banked, Positive = Over-banked)', max_digits=14)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash Deposit'), ('cheque', 'Cheque Deposit'), ('mixed', 'Mixed (Cash & Cheque)'), ('card_settlement', 'Card Batch Settlement (PDQ)'), ('mobile_money', 'Mobile Money Sweeping / Till Bank Transfer')], default='cash', max_length=25)),
                ('deposit_reference', models.CharField(help_text='Bank deposit slip number, transaction reference, or teller code', max_length=100)),
                ('deposit_date', models.DateField(db_index=True, help_text='Date physically banked at the bank')),
                ('slip_image', models.FileField(blank=True, help_text='Photo / scan of bank deposit slip or confirmation receipt', null=True, upload_to='banking/slips/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending / In Transit'), ('banked', 'Banked (Awaiting Statement Match)'), ('matched', 'Matched & Reconciled'), ('discrepancy', 'Discrepancy Flagged')], db_index=True, default='banked', max_length=20)),
                ('variance_reason', models.TextField(blank=True, help_text='Mandatory explanation if variance exceeds threshold')),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banking_records', to='pos.bankaccount')),
                ('branch', models.ForeignKey(blank=True, help_text='Specific branch source (leave blank for central consolidated banking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_records', to='pos.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_records', to='pos.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deposited_by', models.ForeignKey(help_text='Cashier or supervisor who performed the bank run', on_delete=django.db.models.deletion.PROTECT, related_name='banking_deposits_made', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_records_reconciled', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, help_text='Specific till / register if banked by terminal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banking_records', to='pos.posterminal')),
            ],
            options={
                'ordering': ['-deposit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('import_file', models.FileField(blank=True, null=True, upload_to='banking/statements/%Y/%m/')),
                ('file_format', models.CharField(choices=[('csv', 'CSV Spreadsheet'), ('ofx', 'OFX / QBO File'), ('manual', 'Manual Entry Batch')], default='csv', max_length=15)),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('statement_start_date', models.DateField(blank=True, null=True)),
                ('statement_end_date', models.DateField(blank=True, null=True)),
                ('total_lines', models.IntegerField(default=0)),
                ('matched_lines', models.IntegerField(default=0)),
                ('total_credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_debits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_batches', to='pos.bankaccount')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_import_batches', to='pos.business')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statement_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('line_type', models.CharField(choices=[('credit', 'Deposit / Credit (+)'), ('debit', 'Withdrawal / Fee / Debit (-)')], default='credit', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unmatched', 'Unmatched'), ('matched', 'Matched & Reconciled'), ('ignored', 'Ignored / Non-POS Item')], db_index=True, default='unmatched', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='pos.bankaccount')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='pos.bankstatementimportbatch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_lines', to='pos.business')),
                ('matched_banking_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='pos.bankingrecord')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('match_type', models.CharField(choices=[('one_to_one', '1-to-1 Match'), ('many_to_one', 'Combined Deposits to 1 Statement Line'), ('one_to_many', '1 Deposit Split to Multiple Statement Lines'), ('with_fee', 'Match with Bank Fee / Charge Deduction')], default='one_to_one', max_length=20)),
                ('total_banked_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_statement_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank_charge_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bank transaction fees or excise deducted from deposit', max_digits=14)),
                ('variance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('banking_records', models.ManyToManyField(related_name='reconciliation_matches', to='pos.bankingrecord')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_matches', to='pos.business')),
                ('matched_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations_performed', to=settings.AUTH_USER_MODEL)),
                ('statement_lines', models.ManyToManyField(related_name='reconciliation_matches', to='pos.bankstatementline')),
            ],
            options={
                'ordering': ['-matched_at'],
            },
        ),
        migrations.CreateModel(
            name='BankingAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('record_created', 'Banking Record Created'), ('record_updated', 'Banking Record Details Updated'), ('slip_uploaded', 'Deposit Slip Uploaded'), ('statement_imported', 'Bank Statement Imported'), ('manual_line_added', 'Manual Statement Line Added'), ('auto_matched', 'Auto-Matched to Statement Line'), ('manual_matched', 'Manually Reconciled'), ('unmatched', 'Reconciliation Unmatched / Reverted'), ('line_ignored', 'Statement Line Marked as Ignored'), ('discrepancy_flagged', 'Variance Discrepancy Flagged'), ('discrepancy_resolved', 'Discrepancy Resolved with Note')], db_index=True, max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banking_audit_logs', to='pos.business')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('banking_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.bankingrecord')),
                ('statement_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.bankstatementline')),
                ('reconciliation_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pos.reconciliationmatch')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='bankaccount',
            index=models.Index(fields=['business', 'is_active'], name='pos_bankacc_busines_7b87f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together={('business', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='bankingrecord',
            index=models.Index(fields=['business', '-deposit_date'], name='pos_banking_busines_ea9d1c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingrecord',
            index=models.Index(fields=['business', 'status'], name='pos_banking_busines_6a0537_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingrecord',
            index=models.Index(fields=['bank_account', 'status'], name='pos_banking_bank_ac_a95a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['business', 'bank_account', 'status'], name='pos_banksta_busines_64d72f_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatementline',
            index=models.Index(fields=['transaction_date', 'status'], name='pos_banksta_transac_afc123_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingauditlog',
            index=models.Index(fields=['business', '-timestamp'], name='pos_banking_busines_1400dd_idx'),
        ),
        migrations.AddIndex(
            model_name='bankingauditlog',
            index=models.Index(fields=['action', '-timestamp'], name='pos_banking_action_811b7c_idx'),
        ),
    ]
