# Generated by Django 5.1.4 on 2026-09-16 03:13

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0107_bankaccount_bankingrecord_bankstatementimportbatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_number', models.CharField(db_index=True, editable=False, help_text='Format: PKU-YYYYMMDD-XXXX', max_length=30, unique=True)),
                ('witness_type', models.CharField(choices=[('supervisor', 'Supervisor / Manager'), ('peer_cashier', 'Peer Cashier (Witness Fallback)')], default='supervisor', max_length=20)),
                ('tender_type', models.CharField(choices=[('cash', 'Cash (Banknotes/Coins)'), ('cheque', 'Cheques'), ('foreign_currency', 'Foreign Currency'), ('mixed', 'Mixed Tenders')], default='cash', max_length=20)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('pickup_reference', models.CharField(help_text='Bag number, tamper envelope barcode, or slip ID', max_length=100)),
                ('pickup_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('threshold_exceeded', 'Drawer Threshold Exceeded'), ('scheduled', 'Scheduled Cash Lift'), ('end_of_shift', 'End of Shift Drop'), ('count_dispute', 'Count Dispute / Safety Lift'), ('other', 'Other Reason')], default='threshold_exceeded', max_length=30)),
                ('cashier_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('supervisor_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Confirmation'), ('confirmed', 'Confirmed & Locked'), ('in_safe', 'Transferred to Safe'), ('banked', 'Banked in Deposit'), ('disputed', 'Disputed Count'), ('cancelled', 'Cancelled')], db_index=True, default='confirmed', max_length=20)),
                ('is_locked', models.BooleanField(default=True, help_text='Locked after confirmation; amendments require manager override')),
                ('override_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banking_record', models.ForeignKey(blank=True, help_text='Physical bank deposit record this pickup was rolled into', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_pickups', to='pos.bankingrecord')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_pickups', to='pos.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_pickups', to='pos.business')),
                ('cashier', models.ForeignKey(help_text='Cashier operating the till', on_delete=django.db.models.deletion.PROTECT, related_name='initiated_cash_pickups', to=settings.AUTH_USER_MODEL)),
                ('override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_overrides', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_pickups', to='pos.possession')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_pickups', to='pos.shift')),
                ('supervisor', models.ForeignKey(help_text='Supervisor / manager who witnessed and authorized count', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_cash_pickups', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_pickups', to='pos.posterminal')),
            ],
            options={
                'ordering': ['-pickup_time', '-created_at'],
                'indexes': [models.Index(fields=['business', 'status', '-pickup_time'], name='pos_cashpic_busines_49ae2f_idx'), models.Index(fields=['business', 'branch', '-pickup_time'], name='pos_cashpic_busines_65648a_idx'), models.Index(fields=['session', 'status'], name='pos_cashpic_session_7b1a11_idx')],
            },
        ),
    ]
