# Generated by Django 5.1.4 on 2026-09-16 03:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import pos.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0108_cashpickup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='chart_of_accounts_code',
            field=models.CharField(blank=True, default='', help_text='Accounting code e.g. 5100, 5200', max_length=50),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='monthly_budget_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional monthly expenditure ceiling for this category', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='requires_manager_approval_above',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Payout amount above which manager approval PIN/password is mandatory', max_digits=10),
        ),
        migrations.CreateModel(
            name='CashPaidOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_out_number', models.CharField(db_index=True, editable=False, help_text='Format: POUT-YYYYMMDD-XXXX', max_length=30)),
                ('is_petty_cash_fund', models.BooleanField(default=False, help_text='True if disbursed from a standalone petty cash float instead of active till register')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('payee', models.CharField(help_text='Vendor, courier, or individual the cash was given to', max_length=200)),
                ('description', models.TextField(help_text='Purpose of expense / goods or services acquired')),
                ('receipt_reference', models.CharField(blank=True, default='', help_text='Invoice / receipt / slip number once collected', max_length=100)),
                ('receipt_attachment', models.FileField(blank=True, help_text='Photo or scan of vendor receipt', null=True, upload_to='paid_outs/receipts/%Y/%m/')),
                ('receipt_due_by', models.DateTimeField(blank=True, help_text='Deadline for returning receipt (defaults to shift close / end of day)', null=True)),
                ('receipt_received_at', models.DateTimeField(blank=True, null=True)),
                ('has_receipt_exception', models.BooleanField(default=False, help_text='True if manager signed an exception note for informal vendor with no receipt')),
                ('exception_reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('paid_pending_receipt', 'Paid - Pending Receipt'), ('confirmed', 'Confirmed (Receipt Attached / Exception Signed)'), ('rejected', 'Rejected'), ('reversed', 'Reversed (Cash Returned)'), ('written_off', 'Written Off (Lost Receipt Loss)')], db_index=True, default='paid_pending_receipt', max_length=30)),
                ('paid_out_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_reversed', models.BooleanField(default=False)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_by', models.ForeignKey(help_text='Supervisor/Manager who approved the payout', on_delete=django.db.models.deletion.PROTECT, related_name='authorized_paid_outs', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_paid_outs', to='pos.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_paid_outs', to='pos.business')),
                ('category', models.ForeignKey(help_text='Expense category linking to chart of accounts', on_delete=django.db.models.deletion.PROTECT, related_name='paid_outs', to='pos.expensecategory')),
                ('exception_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receipt_exceptions', to=settings.AUTH_USER_MODEL)),
                ('expense_entry', models.ForeignKey(blank=True, help_text='Linked General Ledger Expense entry created upon receipt/exception confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_out_source', to='pos.expense')),
                ('requested_by', models.ForeignKey(help_text='Staff member or cashier who requested the cash', on_delete=django.db.models.deletion.PROTECT, related_name='requested_paid_outs', to=settings.AUTH_USER_MODEL)),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversed_paid_outs', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_paid_outs', to='pos.possession')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_paid_outs', to='pos.shift')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_paid_outs', to='pos.posterminal')),
            ],
            options={
                'ordering': ['-paid_out_time', '-created_at'],
                'indexes': [models.Index(fields=['business', 'status', '-paid_out_time'], name='pos_cashpai_busines_253423_idx'), models.Index(fields=['business', 'branch', '-paid_out_time'], name='pos_cashpai_busines_113b6c_idx'), models.Index(fields=['session', 'status'], name='pos_cashpai_session_210f51_idx'), models.Index(fields=['category', '-paid_out_time'], name='pos_cashpai_categor_377897_idx')],
            },
            bases=(pos.models.CacheInvalidationMixin, pos.models.AuditModelMixin, models.Model),
        ),
    ]
