# Generated by Django 5.1.4 on 2026-09-16 03:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0109_expensecategory_chart_of_accounts_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reason', models.CharField(choices=[('return', 'Goods Returned'), ('damaged_goods', 'Damaged Goods on Delivery'), ('overcharge', 'Invoice Overcharge'), ('discount', 'Discount / Price Rebate'), ('other', 'Other Claim Reason')], default='return', max_length=30)),
                ('date_raised', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('approved_by_supplier', 'Approved by Supplier'), ('applied_to_invoice', 'Applied to Invoice'), ('refunded', 'Refunded by Supplier'), ('partially_resolved', 'Partially Resolved'), ('rejected', 'Rejected')], db_index=True, default='pending_approval', max_length=30)),
                ('resolution_type', models.CharField(choices=[('offset_invoice', 'Offset Future Invoice'), ('cash_refund', 'Cash Refund'), ('bank_refund', 'Bank Refund'), ('mixed', 'Mixed Offset & Refund'), ('unresolved', 'Unresolved')], default='unresolved', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='supplier_credits/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_raised', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, help_text="Supplier's original invoice number or internal reference", max_length=60)),
                ('invoice_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date invoice was issued by supplier')),
                ('due_date', models.DateField(db_index=True, help_text='Payment due date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], db_index=True, default='unpaid', max_length=20)),
                ('attachment', models.FileField(blank=True, help_text='PDF / scan of supplier bill', null=True, upload_to='supplier_invoices/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('received_via', models.CharField(choices=[('bank_transfer', 'Bank Transfer / EFT'), ('cash', 'Cash (Drawer / Safe)'), ('mobile_money', 'Mobile Money')], default='bank_transfer', max_length=20)),
                ('destination_type', models.CharField(choices=[('bank_account', 'Bank Account'), ('cash_drawer', 'Till Cash Drawer'), ('petty_cash', 'Petty Cash Fund')], default='bank_account', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Statement Match'), ('matched', 'Matched & Reconciled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_supplier_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='pos.supplierpayment'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='supplier_payments',
            field=models.ManyToManyField(blank=True, related_name='reconciliation_matches', to='pos.supplierpayment'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='pos.bankaccount'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_payments', to='pos.bankstatementline'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='cash_paid_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to='pos.cashpaidout'),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='payment_method_type',
            field=models.CharField(choices=[('bank_transfer', 'Bank Transfer / EFT'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('mobile_money', 'Mobile Money')], default='bank_transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='reversed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='source_type',
            field=models.CharField(choices=[('bank_account', 'Bank Account / Transfer'), ('cash_drawer', 'Cash Drawer (Till)'), ('petty_cash', 'Petty Cash Fund'), ('direct', 'Direct / Other')], default='bank_account', max_length=20),
        ),
        migrations.AddField(
            model_name='supplierpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval / Transit'), ('sent', 'Sent / Outstanding'), ('cleared', 'Cleared on Bank Statement'), ('reversed', 'Reversed')], db_index=True, default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='paymentallocation',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='pos.purchase'),
        ),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='banking_records',
            field=models.ManyToManyField(blank=True, related_name='reconciliation_matches', to='pos.bankingrecord'),
        ),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='match_type',
            field=models.CharField(choices=[('one_to_one', '1-to-1 Match'), ('many_to_one', 'Combined Records to 1 Statement Line'), ('one_to_many', '1 Record Split to Multiple Statement Lines'), ('with_fee', 'Match with Bank Fee / Charge Deduction')], default='one_to_one', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.paymentmethod'),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='payment_number',
            field=models.CharField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='supplierpayment',
            name='reference_number',
            field=models.CharField(blank=True, help_text='EFT reference, Cheque #, Mobile Money Tx ID', max_length=100),
        ),
        migrations.AddIndex(
            model_name='supplierpayment',
            index=models.Index(fields=['business', 'status'], name='pos_supplie_busines_27dda8_idx'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_credits_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_credits', to='pos.business'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_credits_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='related_grn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_credits', to='pos.goodsreturnednote'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='related_purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_credits', to='pos.purchase'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credits', to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercreditapplication',
            name='applied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suppliercreditapplication',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='pos.suppliercredit'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_invoices', to='pos.business'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='goods_received_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pos.goodsreceivednote'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='pos.purchase'),
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='suppliercreditapplication',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='pos.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='related_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='pos.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='suppliercredit',
            name='resolution_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_credits', to='pos.supplierinvoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_allocations', to='pos.supplierinvoice'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['invoice'], name='pos_payment_invoice_171461_idx'),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='bank_statement_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_refunds', to='pos.bankstatementline'),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_refunds', to='pos.business'),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_refunds', to='pos.bankaccount'),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_refunds_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierrefund',
            name='supplier_credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='pos.suppliercredit'),
        ),
        migrations.AddField(
            model_name='bankstatementline',
            name='matched_supplier_refund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_statement_lines', to='pos.supplierrefund'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='supplier_refunds',
            field=models.ManyToManyField(blank=True, related_name='reconciliation_matches', to='pos.supplierrefund'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['business', 'status'], name='pos_supplie_busines_1b7727_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['supplier', 'status'], name='pos_supplie_supplie_09a752_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierinvoice',
            index=models.Index(fields=['due_date', 'status'], name='pos_supplie_due_dat_e7391b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierinvoice',
            unique_together={('business', 'supplier', 'invoice_number')},
        ),
        migrations.AddIndex(
            model_name='suppliercreditapplication',
            index=models.Index(fields=['credit'], name='pos_supplie_credit__db66fc_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercreditapplication',
            index=models.Index(fields=['invoice'], name='pos_supplie_invoice_18e296_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercredit',
            index=models.Index(fields=['business', 'status'], name='pos_supplie_busines_0003d5_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercredit',
            index=models.Index(fields=['supplier', 'status'], name='pos_supplie_supplie_7941e3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliercredit',
            unique_together={('business', 'credit_number')},
        ),
        migrations.AddIndex(
            model_name='supplierrefund',
            index=models.Index(fields=['business', 'status'], name='pos_supplie_busines_6c46cc_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierrefund',
            index=models.Index(fields=['received_date'], name='pos_supplie_receive_294e3d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplierrefund',
            unique_together={('business', 'refund_number')},
        ),
    ]
