# Generated by Django 5.1.4 on 2026-09-30 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0110_suppliercredit_suppliercreditapplication_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSGLMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_account_code', models.CharField(default='1010', help_text='Till Cash Account (default: 1010)', max_length=20)),
                ('mpesa_account_code', models.CharField(default='1030', help_text='M-Pesa Clearing (default: 1030)', max_length=20)),
                ('card_account_code', models.CharField(default='1040', help_text='Card / Swipe Clearing (default: 1040)', max_length=20)),
                ('credit_account_code', models.CharField(default='1100', help_text='Accounts Receivable (default: 1100)', max_length=20)),
                ('sales_revenue_code', models.CharField(default='4000', help_text='Sales Revenue Account (default: 4000)', max_length=20)),
                ('vat_output_code', models.CharField(default='2100', help_text='VAT Output Account (default: 2100)', max_length=20)),
                ('cogs_account_code', models.CharField(default='5000', help_text='COGS Account (default: 5000)', max_length=20)),
                ('inventory_account_code', models.CharField(default='1200', help_text='Inventory Asset Account (default: 1200)', max_length=20)),
                ('cash_variance_code', models.CharField(default='6900', help_text='Cash Short/Over Account (default: 6900)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gl_mapping', to='pos.business')),
            ],
            options={
                'verbose_name': 'POS GL Mapping',
                'verbose_name_plural': 'POS GL Mappings',
            },
        ),
    ]
