# Generated by Django 5.1.4 on 2026-10-01 17:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0111_posglmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='total_damaged_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='total_ordered_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceivednote',
            name='total_received_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceivednoteitem',
            name='quantity_damaged',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceivednoteitem',
            name='quantity_ordered',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceivednoteitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreturnednoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Quantity ordered', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity_damaged',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Quantity damaged or missing', max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity_received',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Actual quantity received (good items)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salereturnitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='new_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='previous_quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='quantity_change',
            field=models.DecimalField(decimal_places=3, help_text='Positive for additions, negative for deductions', max_digits=12),
        ),
    ]
