# Generated by Django 5.1.4 on 2026-04-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0098_hscode_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBackupSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_mode', models.CharField(choices=[('automatic', 'Automatic'), ('scheduled', 'Scheduled'), ('manual', 'Manual')], default='automatic', max_length=20)),
                ('schedule_interval_hours', models.IntegerField(blank=True, null=True)),
                ('retention_days', models.IntegerField(default=30)),
                ('local_storage_limit_mb', models.IntegerField(blank=True, null=True)),
                ('storage_mode', models.CharField(choices=[('local_only', 'Local Only'), ('cloud_only', 'Cloud Only'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('encryption_key_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_settings', to='pos.business')),
            ],
            options={
                'verbose_name': 'Tenant Backup Settings',
                'verbose_name_plural': 'Tenant Backup Settings',
            },
        ),
        migrations.CreateModel(
            name='BackupSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('storage_key', models.CharField(max_length=500)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('encryption_key_id', models.CharField(blank=True, max_length=200)),
                ('event_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('corrupted', 'Corrupted'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_snapshots', to='pos.business')),
            ],
            options={
                'verbose_name': 'Backup Snapshot',
                'verbose_name_plural': 'Backup Snapshots',
                'ordering': ['tenant', 'version'],
                'unique_together': {('tenant', 'version')},
            },
        ),
    ]
