# Generated by Django 5.1.4 on 2026-09-29 23:50

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_kenyabank_kenyacounty_journalentry_journalentryline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='e.g. 1010, 2100, 4000', max_length=20)),
                ('name', models.CharField(db_index=True, help_text='e.g. Cash in Till, VAT Output Payable', max_length=150)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('current_asset', 'Current Asset'), ('cash_and_bank', 'Cash and Bank Equivalents'), ('accounts_receivable', 'Accounts Receivable (Trade Debtors)'), ('inventory', 'Merchandise Inventory'), ('statutory_tax_asset', 'Statutory Tax Credits & Claimable VAT'), ('fixed_asset', 'Property, Plant & Equipment'), ('accumulated_depreciation', 'Accumulated Depreciation'), ('current_liability', 'Current Liability'), ('accounts_payable', 'Accounts Payable (Trade Creditors)'), ('statutory_tax_liability', 'Statutory Tax & Remittance Liabilities'), ('payroll_clearing', 'Payroll Clearing & Net Salaries'), ('long_term_liability', 'Long-Term Borrowings & Liabilities'), ('equity', 'Owner / Share Capital'), ('retained_earnings', 'Retained Earnings / Accumulated Reserves'), ('owner_drawing', 'Owner Drawings & Dividends Paid'), ('operating_revenue', 'Operating Sales Revenue'), ('sales_discount', 'Sales Discounts & Allowances'), ('other_income', 'Other Income & Net Gains'), ('cost_of_sales', 'Cost of Goods Sold (Direct Costs)'), ('payroll_expense', 'Salaries, Wages & Employer Statutory Costs'), ('operating_expense', 'Operating & Administrative Expenses'), ('financial_expense', 'Bank Charges & Financial Fees'), ('depreciation_expense', 'Depreciation & Amortization'), ('tax_expense', 'Income Tax & Corporate Tax')], db_index=True, max_length=40)),
                ('normal_balance', models.CharField(choices=[('debit', 'Debit (DR)'), ('credit', 'Credit (CR)')], default='debit', max_length=10)),
                ('currency', models.CharField(default='KES', help_text='ISO 4217 Currency Code', max_length=3)),
                ('is_system', models.BooleanField(db_index=True, default=False, help_text='System-managed account (e.g. Retained Earnings, Control Accounts). Cannot be deleted.')),
                ('system_tag', models.CharField(blank=True, db_index=True, help_text="Canonical tag for system mapping (e.g. 'ar', 'ap', 'vat_output', 'retained_earnings')", max_length=50, null=True)),
                ('is_reconciliation', models.BooleanField(default=False, help_text='Designates this account for bank/cash statement reconciliation')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Locked accounts disallow manual postings')),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent account for hierarchical reporting', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chart of Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="e.g. 'FY 2026'", max_length=50)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_closed_fiscal_years', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_reopened_fiscal_years', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_number', models.PositiveSmallIntegerField(help_text='1 to 12 (or 13 for Year-End Adjustments)')),
                ('name', models.CharField(help_text="e.g. 'January 2026'", max_length=50)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('is_closed', models.BooleanField(db_index=True, default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('is_adjustment_period', models.BooleanField(default=False, help_text='True for Period 13 year-end adjusting entries')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_closed_periods', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_reopened_periods', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear')),
            ],
            options={
                'verbose_name': 'Fiscal Period',
                'verbose_name_plural': 'Fiscal Periods',
                'ordering': ['fiscal_year__start_date', 'period_number'],
                'unique_together': {('company', 'fiscal_year', 'period_number')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_number', models.CharField(db_index=True, help_text='e.g. JRN-202609-0001', max_length=50)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual General Journal'), ('sales_close', 'POS Sales / Shift Close'), ('payroll', 'Payroll Run Journal'), ('ar_invoice', 'Customer Invoice'), ('ap_bill', 'Supplier Bill'), ('payment', 'Payment Voucher / Disbursement'), ('receipt', 'Customer Collection / Receipt'), ('bank_reconciliation', 'Bank Reconciliation Adjustment'), ('depreciation', 'Fixed Asset Depreciation'), ('reversing', 'Reversing Journal Entry'), ('recurring', 'Recurring Journal Entry'), ('closing', 'Year-End Closing Entry'), ('adjustment', 'Period-End Adjustment')], db_index=True, default='manual', max_length=30)),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('source_module', models.CharField(db_index=True, default='accounting', help_text='e.g. pos, hr, manual', max_length=50)),
                ('source_ref', models.CharField(blank=True, db_index=True, help_text='Origin doc reference e.g. ZREP-20260930-01', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, help_text='Unique key ensuring exactly-once posting', max_length=150, null=True)),
                ('narration', models.TextField(help_text='Transaction description and business purpose')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('posted', 'Posted'), ('reversed', 'Reversed')], db_index=True, default='posted', max_length=20)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurring_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], max_length=20)),
                ('recurring_end_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch/Outlet this entity belongs to (NULL for company-wide)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_branch_set', to='core.branch')),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('fiscal_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.fiscalperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_posted_journals', to=settings.AUTH_USER_MODEL)),
                ('reversal_entry', models.ForeignKey(blank=True, help_text='Pointer to the countervailing reversing journal entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses_entry', to='accounting.journalentry')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_reversed_journals', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(db_index=True, max_length=20)),
                ('account_name', models.CharField(max_length=150)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('currency', models.CharField(default='KES', help_text='Transaction Currency (e.g. KES, USD)', max_length=3)),
                ('foreign_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=12)),
                ('cost_center', models.CharField(blank=True, db_index=True, help_text="e.g. 'CC-SALES', 'CC-OPS'", max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.account')),
                ('branch', models.ForeignKey(blank=True, help_text='Analytic branch dimension', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_journal_lines', to='core.branch')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Entry Line',
                'verbose_name_plural': 'Journal Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PostingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_module', models.CharField(db_index=True, max_length=50)),
                ('source_ref', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(help_text='Serialized journal lines and metadata')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_postings', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Posting Queue',
                'verbose_name_plural': 'Posting Queue Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('company', 'idempotency_key'), name='unique_company_accounting_idempotency_key'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('company', 'entry_number')},
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='accounting_line_non_negative_amounts'),
        ),
        migrations.AddConstraint(
            model_name='journalentryline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debit__gt', 0), ('credit', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='accounting_line_either_debit_or_credit'),
        ),
    ]
