# Generated by Django 5.1.4 on 2026-09-30 04:14

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_bankaccount_bankstatement_bankreconciliation_and_more'),
        ('core', '0004_kenyabank_kenyacounty_journalentry_journalentryline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendorbillline',
            options={},
        ),
        migrations.AlterField(
            model_name='customerinvoiceline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='vendorbillline',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.CreateModel(
            name='WithholdingTaxRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wht_type', models.CharField(choices=[('payable', 'WHT Payable (Deducted from Supplier)'), ('receivable', 'WHT Receivable (Deducted by Customer)')], db_index=True, max_length=20)),
                ('category', models.CharField(choices=[('management_professional', 'Management / Professional Fees (5%)'), ('contractual', 'Contractual Services (3%)'), ('rent', 'Commercial Rent (10%)'), ('whvat', 'Withholding VAT (2%)'), ('other', 'Other Prescribed Rate')], db_index=True, default='whvat', max_length=40)),
                ('party_name', models.CharField(max_length=255)),
                ('party_pin', models.CharField(blank=True, help_text='KRA PIN e.g. P051234567Z', max_length=20)),
                ('transaction_date', models.DateField(db_index=True)),
                ('base_amount', models.DecimalField(decimal_places=2, help_text='Gross taxable value', max_digits=14)),
                ('rate_percentage', models.DecimalField(decimal_places=2, help_text='Tax rate e.g. 2.00, 5.00', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Amount of tax withheld', max_digits=14)),
                ('certificate_number', models.CharField(blank=True, help_text='KRA WHT Certificate Number', max_length=100)),
                ('is_remitted', models.BooleanField(default=False, help_text='Marked True when remitted to KRA via iTax')),
                ('remittance_date', models.DateField(blank=True, null=True)),
                ('remittance_reference', models.CharField(blank=True, help_text='KRA Payment Slip / E-Slip No.', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(help_text='Tenant company owning this entity', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_company_set', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_set', to=settings.AUTH_USER_MODEL)),
                ('customer_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_records', to='accounting.customerinvoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_records', to='accounting.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_set', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_records', to='accounting.vendorbill')),
            ],
            options={
                'verbose_name': 'Withholding Tax Record',
                'verbose_name_plural': 'Withholding Tax Records',
                'ordering': ['-transaction_date', '-id'],
            },
        ),
    ]
